// Script compilation used only by agdta_test (agdta loads pre-built .o files).

#include "agdta_test_compile.h"
#include "project.h"
#include "game_data.h"
#include "script_api_versions.h"
#include "script_defs.h"

#include "util/file_helpers.h"
#include "util/path_helpers.h"

#include "script/cs_compiler.h"
#include "script/cc_common.h"
#include "script/cc_script.h"
#include "preproc/preprocessor.h"

#include "util/file.h"
#include "data/dialogscriptconv.h"
#include "data/script_utils.h"
#include "data/scriptgen.h"

#include <cstdio>
#include <fstream>
#include <memory>
#include <string>
#include <vector>

namespace AGSBuild
{

using AGS::Common::PathExists;
using AGS::Common::ReadTextFile;

#define Log(...) ((void)0)

// -------------------------------------------------------------------------
// Auto-generated script header (_AutoGenerated.ash)
// Mirrors the C# editor's Tasks.RegenerateScriptHeader()
// -------------------------------------------------------------------------

// Build a GameRef from the editor's GameData — provides the bridge between
// the editor's rich data model and the lightweight scriptgen structures.
static AGS::DataUtil::GameRef BuildGameRef(const GameData& gd)
{
    using namespace AGS::DataUtil;
    GameRef ref;

    // Helper: strip non-alphanumeric characters (except underscore) from names,
    // matching the sanitization in agfreader's ReadEntityRef.
    auto sanitize = [](const std::string& name) -> String {
        String result;
        for (char ch : name)
        {
            if (std::isalnum(static_cast<unsigned char>(ch)) || ch == '_')
                result.AppendChar(ch);
        }
        return result;
    };

    // Audio clips
    for (const auto& ac : gd.audio_clips)
    {
        EntityRef e;
        e.TypeName = "AudioClip";
        e.ID = ac.id;
        e.ScriptName = sanitize(ac.name);
        ref.AudioClips.push_back(e);
    }

    // Audio clip types
    for (const auto& at : gd.audio_clip_types)
    {
        EntityRef e;
        e.ID = at.id;
        e.ScriptName = sanitize(at.name);
        ref.AudioTypes.push_back(e);
    }

    // Characters
    for (const auto& ch : gd.characters)
    {
        CharacterRef e;
        e.TypeName = "Character";
        e.ID = ch.id;
        e.ScriptName = sanitize(ch.script_name);
        ref.Characters.push_back(e);
    }

    // Cursors
    for (const auto& c : gd.cursors)
    {
        EntityRef e;
        e.ID = c.id;
        e.ScriptName = sanitize(c.name);
        ref.Cursors.push_back(e);
    }

    // Dialogs
    for (const auto& d : gd.dialogs)
    {
        DialogRef dr;
        dr.TypeName = "Dialog";
        dr.ID = d.id;
        dr.ScriptName = sanitize(d.script_name);
        dr.OptionCount = d.option_count;
        ref.Dialogs.push_back(dr);
    }

    // Fonts
    for (const auto& f : gd.fonts)
    {
        EntityRef e;
        e.ID = f.id;
        e.ScriptName = sanitize(f.name);
        ref.Fonts.push_back(e);
    }

    // GUIs (with controls)
    for (const auto& g : gd.guis)
    {
        GUIRef gr;
        gr.TypeName = "GUI";
        gr.ID = g.id;
        gr.ScriptName = sanitize(g.name);
        for (const auto& ctrl : g.controls)
        {
            EntityRef ce;
            ce.ID = ctrl.id;
            ce.ScriptName = sanitize(ctrl.name);
            // Map type_tag to script class type (matches C# GUIControl.ScriptClassType)
            if (ctrl.type_tag == "GUIButton")          ce.TypeName = "Button";
            else if (ctrl.type_tag == "GUILabel")      ce.TypeName = "Label";
            else if (ctrl.type_tag == "GUISlider")     ce.TypeName = "Slider";
            else if (ctrl.type_tag == "GUIListBox")    ce.TypeName = "ListBox";
            else if (ctrl.type_tag == "GUITextBox")    ce.TypeName = "TextBox";
            else if (ctrl.type_tag == "GUIInventory")  ce.TypeName = "InvWindow";
            else if (ctrl.type_tag == "GUITextWindowEdge") ce.TypeName = "Button";
            gr.Controls.push_back(ce);
        }
        ref.GUI.push_back(gr);
    }

    // Inventory items
    for (const auto& inv : gd.inventory_items)
    {
        EntityRef e;
        e.TypeName = "InventoryItem";
        e.ID = inv.id;
        e.ScriptName = sanitize(inv.script_name);
        ref.Inventory.push_back(e);
    }

    // Views
    for (const auto& v : gd.views)
    {
        EntityRef e;
        e.ID = v.id;
        e.ScriptName = sanitize(v.name);
        ref.Views.push_back(e);
    }

    // Global variables
    for (const auto& gv : gd.global_variables)
    {
        Variable var;
        var.Type = gv.type_name.c_str();
        var.Name = gv.name.c_str();
        var.Value = gv.default_value.c_str();
        ref.GlobalVars.push_back(var);
    }

    // Settings
    ref.Settings.SayFunction = gd.dialog_say_function.c_str();
    ref.Settings.NarrateFunction = gd.dialog_narrate_function.c_str();

    return ref;
}

static std::vector<AGS::DataUtil::Variable> BuildScriptGlobalVariables(const GameData& gd)
{
    std::vector<AGS::DataUtil::Variable> vars;
    vars.reserve(gd.global_variables.size());
    for (const auto& gv : gd.global_variables)
    {
        AGS::DataUtil::Variable var;
        var.Name = gv.name.c_str();
        var.Type = gv.type_name.c_str();
        if (gv.type_name == "bool" && !gv.default_value.empty())
        {
            AGS::Common::String value(gv.default_value.c_str());
            value.MakeLower();
            var.Value = value;
        }
        else
        {
            var.Value = gv.default_value.c_str();
        }
        vars.push_back(var);
    }
    return vars;
}

static bool GenerateAutoHeader(const GameData& gd, std::string& out_header)
{
    AGS::DataUtil::GameRef game_ref = BuildGameRef(gd);
    AGS::DataUtil::String header = AGS::DataUtil::MakeGameAutoScriptHeader(game_ref);
    out_header = header.GetCStr();
    return true;
}

// -------------------------------------------------------------------------
// Configure a fresh preprocessor with all macros driven by game settings.
// Matches the C# editor's DefineMacrosAccordingToGameSettings().
// -------------------------------------------------------------------------
static void ConfigurePreprocessor(AGS::Preprocessor::Preprocessor& pp,
                                   const GameData& gd,
                                   const BuildConfig& config)
{
    pp.SetAppVersion("3.6.3");

    pp.DefineMacro("AGS_SUPPORTS_IFVER", "1");
    if (gd.enforce_new_strings)
        pp.DefineMacro("AGS_NEW_STRINGS", "1");

    // STRICT macro: The modern agsdefns.sh from our repo moves more functions
    // (GetGlobalInt, SetGlobalInt, etc.) behind #ifndef STRICT than older versions
    // did. Old projects (pre-3.4.0) were created when those functions were still
    // available with STRICT. To avoid false compile errors with old projects when
    // using the modern agsdefns.sh, only define STRICT for projects saved with
    // AGS 3.4.0 or later.
    {
        bool is_old_project = false;
        if (!gd.saved_editor_version.empty())
        {
            int major = 0, minor = 0, patch = 0;
            sscanf(gd.saved_editor_version.c_str(), "%d.%d.%d", &major, &minor, &patch);
            if (major < 3 || (major == 3 && minor < 4))
                is_old_project = true;
        }
        if (gd.enforce_object_scripting && !is_old_project)
            pp.DefineMacro("STRICT", "1");
    }

    if (gd.left_to_right_precedence)
        pp.DefineMacro("LRPRECEDENCE", "1");
    if (gd.enforce_new_strings)
        pp.DefineMacro("STRICT_STRINGS", "1");
    if (gd.enforce_new_audio)
        pp.DefineMacro("STRICT_AUDIO", "1");
    if (!gd.use_old_custom_dialog_api)
        pp.DefineMacro("NEW_DIALOGOPTS_API", "1");
    if (!gd.use_old_keyboard_handling)
        pp.DefineMacro("NEW_KEYINPUT_API", "1");

    if (gd.debug_mode)
        pp.DefineMacro("DEBUG", "1");

    int api_ver = gd.script_api_version;
    for (int i = 0; i < kScriptAPIVersionCount; i++)
    {
        std::string macro = "SCRIPT_API_" + std::string(kScriptAPIVersions[i].name);
        pp.DefineMacro(macro.c_str(), "1");
        if (api_ver != kScriptAPIHighest &&
            kScriptAPIVersions[i].value >= api_ver)
            break;
    }

    int compat_ver = gd.script_compat_level;
    if (compat_ver == kScriptAPIHighest)
        compat_ver = kScriptAPIVersions[kScriptAPIVersionCount - 1].value;
    for (int i = 0; i < kScriptAPIVersionCount; i++)
    {
        if (kScriptAPIVersions[i].value >= compat_ver)
        {
            std::string macro = "SCRIPT_COMPAT_" + std::string(kScriptAPIVersions[i].name);
            pp.DefineMacro(macro.c_str(), "1");
        }
    }
}

// -------------------------------------------------------------------------
// Preprocess all accumulated raw headers + a script body using a FRESH
// preprocessor, then set up ccDefaultHeaders and compile.
// Matches the C# editor's per-module CompileScript() pattern:
//   1. Create fresh Preprocessor (clean macro state)
//   2. Preprocess each raw header in order
//   3. Preprocess the script body
//   4. ccRemoveDefaultHeaders() + ccAddDefaultHeader() for each header
//   5. ccCompileText() with the preprocessed body
// This avoids macro state leaking between modules (e.g. agsdefns.sh
// #define/#undef cycles causing "macro already defined" errors).
// -------------------------------------------------------------------------
struct RawHeader
{
    std::string text;
    std::string name;
};

static ccScript* PreprocessAndCompile(
    const GameData& gd, const BuildConfig& config,
    const std::vector<RawHeader>& raw_headers,
    const std::string& script_text, const std::string& script_name,
    BuildResult& result, const std::string& module_name,
    const std::string& temp_dir)
{
    // Fresh preprocessor per module — no macro state carried over
    AGS::Preprocessor::Preprocessor pp;
    ConfigurePreprocessor(pp, gd, config);

    // Preprocess all accumulated headers from scratch
    std::vector<AGS::Common::String> pp_headers;
    pp_headers.reserve(raw_headers.size());
    for (const auto& hdr : raw_headers)
    {
        AGS::Common::String pp_hdr = pp.Preprocess(
            hdr.text.c_str(), hdr.name.c_str());
        const auto& pp_err = pp.GetLastError();
        if (pp_err.Type != AGS::Preprocessor::ErrorCode::None)
        {
            result.AddError(hdr.name, 0,
                std::string("Preprocessor error in header: ") +
                pp_err.Message.GetCStr(), module_name);
            return nullptr;
        }
        pp_headers.push_back(pp_hdr);
    }

    // Preprocess script body
    AGS::Common::String pp_script = pp.Preprocess(
        script_text.c_str(), script_name.c_str());
    {
        const auto& pp_err = pp.GetLastError();
        if (pp_err.Type != AGS::Preprocessor::ErrorCode::None)
        {
            result.AddError(script_name, 0,
                std::string("Preprocessor error: ") +
                pp_err.Message.GetCStr(), module_name);
            return nullptr;
        }
    }

    // DEBUG: dump preprocessed script
    if (!temp_dir.empty())
    {
        std::string dump_path = temp_dir + "/" + module_name + "_pp_script.txt";
        std::ofstream dump(dump_path);
        if (dump.is_open())
            dump << pp_script.GetCStr();
    }

    // Set up native compiler headers: clear all prior, re-add preprocessed
    ccRemoveDefaultHeaders();
    for (size_t i = 0; i < pp_headers.size(); i++)
    {
        ccAddDefaultHeader(pp_headers[i].GetCStr(), raw_headers[i].name.c_str());
    }

    // Compile
    cc_clear_error();
    ccScript* compiled = ccCompileText(pp_script.GetCStr(), module_name.c_str());

    if (!compiled || cc_has_error())
    {
        const ScriptError& err = cc_get_error();
        std::string error_msg = err.HasError
            ? err.ErrorString.GetCStr()
            : "Unknown compilation error";
        int error_line = err.HasError ? err.Line : 0;

        result.AddError(script_name, error_line, error_msg, module_name);
        return nullptr;
    }

    return compiled;
}

// -------------------------------------------------------------------------
// Full script compilation pipeline
// Mirrors the C# editor's AGSEditor.CompileScripts()
// Order: auto-header -> internal headers -> script module headers+bodies -> dialog scripts
//
// Key design (matching C# editor):
//   - Raw (unpreprocessed) header texts accumulate as modules are processed
//   - For each module, a FRESH preprocessor re-processes all accumulated
//     headers + the module body. This prevents macro state leaking between
//     modules and avoids the "macro already defined" error.
//   - ccRemoveDefaultHeaders() + ccAddDefaultHeader() are called per module
// -------------------------------------------------------------------------
bool CompileFixtureScripts(Project& project, const BuildConfig& config,
                             BuildResult& result)
{
    GameData* gd = project.GetGameData();
    if (!gd) return false;

    std::string temp_dir = config.output_base_dir + "/_temp";

    // --- Setup compiler options (driven by game settings) ---
    ccSetSoftwareVersion("3.6.3");
    ccSetOption(SCOPT_EXPORTALL, 1);
    ccSetOption(SCOPT_LINENUMBERS, 1);
    ccSetOption(SCOPT_LEFTTORIGHT, gd->left_to_right_precedence ? 1 : 0);
    ccSetOption(SCOPT_OLDSTRINGS, gd->enforce_new_strings ? 0 : 1);

    // Accumulate raw (unpreprocessed) header texts. Each module compilation
    // creates a fresh Preprocessor and re-preprocesses ALL headers from scratch.
    // This matches the C# editor pattern and avoids macro state leaking.
    std::vector<RawHeader> raw_headers;

    // --- 0. Load built-in header (agsdefns.sh) - store raw text ---
    {
        std::string builtin_header;
        std::string loaded_from;
        if (!LoadBuiltInScriptDefinitions(builtin_header, &loaded_from))
        {
            result.AddError("", 0, FormatBuiltInScriptDefinitionSearchFailure());
            return false;
        }

        Log("[Build] Loaded built-in script definitions: %s (%d bytes)",
            loaded_from.c_str(), (int)builtin_header.size());
        raw_headers.push_back({builtin_header, "_BuiltInScriptHeader"});
    }

    // --- Generate auto-header ---
    std::string auto_header;
    if (!GenerateAutoHeader(*gd, auto_header))
    {
        result.AddError("", 0, "Failed to generate auto-header.");
        return false;
    }

    Log("[Build] Generated _AutoGenerated.ash (%d bytes)", (int)auto_header.size());

    // --- Accumulate raw headers and compile each module ---
    // Raw auto-generated header
    raw_headers.push_back({auto_header, "_AutoGenerated"});

    // Step 1b: Generate and compile _GlobalVariables module
    if (!gd->global_variables.empty())
    {
        std::vector<AGS::DataUtil::Variable> gv_vars = BuildScriptGlobalVariables(*gd);
        const std::string gv_header =
            AGS::DataUtil::MakeVariablesScriptHeader(gv_vars).GetCStr();
        raw_headers.push_back({gv_header, "_GlobalVariables"});

        const std::string gv_body =
            AGS::DataUtil::MakeVariablesScriptBody(gv_vars).GetCStr();

        // Compile _GlobalVariables using fresh-preprocessor pattern
        ccScript* gv_compiled = PreprocessAndCompile(
            *gd, config, raw_headers, gv_body, "_GlobalVariables.asc",
            result, "_GlobalVariables", temp_dir);

        if (!gv_compiled)
            return false;

        // Write compiled script to temp file
        std::string gv_obj_path = temp_dir + "/_GlobalVariables.o";
        {
            std::unique_ptr<AGS::Common::Stream> out(
                AGS::Common::File::CreateFile(gv_obj_path.c_str()));
            if (out)
            {
                gv_compiled->Write(out.get());
            }
            else
            {
                result.AddError("", 0, "Failed to write compiled script: " + gv_obj_path);
                delete gv_compiled;
                return false;
            }
        }

        delete gv_compiled;

        Log("[Build] _GlobalVariables compiled (%d variables).", (int)gd->global_variables.size());
    }

    // Step 2: Compile each script module
    int module_count = (int)gd->script_modules.size();
    int compiled_count = 0;

    for (int i = 0; i < module_count; i++)
    {
        const auto& mod = gd->script_modules[i];
            Log("[Build] Compiling module: %s", mod.name.c_str());

        // Read header file (if exists) and accumulate raw text
        // (matching C# pattern: headers.Add(scripts.Header) before CompileScript)
        if (!mod.header_file.empty())
        {
            std::string header_path = FindFileCaseInsensitive(
                project.GetProjectDir(), mod.header_file);
            if (PathExists(header_path))
            {
                std::string header_content;
                ReadTextFile(header_path, header_content);
                if (!header_content.empty())
                {
                    std::string hdr_name = mod.name + "_header";
                    raw_headers.push_back({header_content, hdr_name});
                }
            }
            else
            {
                Log("[Build]   Warning: header file not found: %s", header_path.c_str());
            }
        }

        // Read script body (case-insensitive lookup for Windows projects on Linux)
        std::string script_content;
        if (!mod.script_file.empty())
        {
            std::string script_path = FindFileCaseInsensitive(
                project.GetProjectDir(), mod.script_file);
            if (PathExists(script_path))
            {
                ReadTextFile(script_path, script_content);
            }
            else
            {
                Log("[Build]   Error: script file not found: %s", script_path.c_str());
                result.AddError(mod.script_file, 0,
                    "Script file not found: " + script_path, mod.name);
                return false;
            }
        }

        if (script_content.empty())
        {
            Log("[Build]   Skipping module '%s' (no script body)", mod.name.c_str());
            continue;
        }

        // Compile with fresh preprocessor (re-processes all headers from scratch)
        ccScript* compiled = PreprocessAndCompile(
            *gd, config, raw_headers, script_content, mod.script_file,
            result, mod.name, temp_dir);

        if (!compiled)
            return false;

        // Write compiled script object to temp file
        std::string obj_path = temp_dir + "/" + mod.name + ".o";
        {
            std::unique_ptr<AGS::Common::Stream> out(
                AGS::Common::File::CreateFile(obj_path.c_str()));
            if (out)
            {
                compiled->Write(out.get());
            }
            else
            {
                result.AddError("", 0, "Failed to write compiled script: " + obj_path);
                delete compiled;
                return false;
            }
        }

        compiled_count++;
        delete compiled;

        Log("[Build]   %s compiled successfully.", mod.name.c_str());
    }

    Log("[Build] Script compilation complete: %d/%d modules compiled.",
        compiled_count, module_count);

    // Empty dialog script unit (required by game28.dta layout).
    {
        const std::string dialog_body = AGS::DataUtil::DialogScriptDefault;
        ccScript* dlg_compiled = PreprocessAndCompile(
            *gd, config, raw_headers, dialog_body, "__DialogScripts",
            result, "__DialogScripts", temp_dir);
        if (!dlg_compiled)
            return false;

        const std::string dlg_obj_path = temp_dir + "/__DialogScripts.o";
        std::unique_ptr<AGS::Common::Stream> out(
            AGS::Common::File::CreateFile(dlg_obj_path.c_str()));
        if (!out)
        {
            result.AddError("", 0,
                "Failed to write compiled dialog script: " + dlg_obj_path);
            delete dlg_compiled;
            return false;
        }
        dlg_compiled->Write(out.get());
        delete dlg_compiled;
    }

    return true;
}


} // namespace AGSBuild
