#!/bin/bash

unset DEVROOT SDKROOT CFLAGS CC LD CPP CXX AR AS NM CXXCPP RANLIB LDFLAGS CPPFLAGS CXXFLAGS

export NDK_PLATFORM_NAME=$(basename $(pwd))
export NDK_ADDITIONAL_LIBRARY_PATH=$(pwd)/../../nativelibs/$NDK_PLATFORM_NAME
export NDK_HOST_NAME=$1

export CC=$NDK_HOST_NAME-gcc
