//=============================================================================
//
// Adventure Game Studio (AGS)
//
// Copyright (C) 1999-2011 Chris Jones and 2011-2026 various contributors
// The full list of copyright holders can be found in the Copyright.txt
// file, which is part of this source code distribution.
//
// The AGS source code is provided under the Artistic License 2.0.
// A copy of this license can be found in the file License.txt and at
// https://opensource.org/license/artistic-2-0/
//
//=============================================================================
// 
// AGS game build utility.
// Uses a collection of AGS cli tools, compiles and builds the generic game
// package, using AGS game project and miscelaneous project files as input.
// 
//=============================================================================
#include <cstdio>
#include "platform/platform.h"
#if (AGS_PLATFORM_OS_WINDOWS)
#include "platform/windows/windows.h"
#endif
#include "data/agfreader.h"
#include "util/cmdlineopts.h"
#include "util/directory.h"
#include "util/file.h"
#include "util/memory_compat.h"
#include "util/path.h"
#include "util/string_utils.h"
#include "util/textstreamreader.h"
#include "util/textstreamwriter.h"
#include "pipedprocess.h"
#include "taskmanager.h"

using namespace AGS;
using namespace AGS::Common;

const char *ToolAgfExport       = "agfexport";
const char *ToolAgf2Dta         = "agf2dta";
const char *ToolDlgAsc          = "agf2dlgasc";
const char *ToolAgsPak          = "agspak";
const char *ToolCrmPak          = "crmpak";
const char *ToolTrac            = "trac";
const char *ToolSpriteImport    = "spriteimport";
const char *ScriptCompiler      = "agscc";
const char *ScriptAPIHeader     = "agsdefns.sh";
const char *ScriptAutoHeader    = "_AutoGenerated.ash";
const char *ScriptGlvarHeader   = "_GlobalVariables.ash";
const char *ScriptGlvarScript   = "_GlobalVariables.asc";
const char *ScriptGlvarScom     = "_GlobalVariables.o";
const char *ScriptDialogScript  = "__DialogScripts.asc";
const char *ScriptDialogScom    = "__DialogScripts.o";

// Separator character for AGSCC's header list
#if (AGS_PLATFORM_OS_WINDOWS)
    #define AGSCC_H_SEP ";"
#else
    #define AGSCC_H_SEP ":"
#endif


using namespace AGSBuild;

struct BuildOptions
{
    static const uint32_t MinThreads = 1u;
    static const uint32_t MaxThreads = 32u;
    static const uint32_t DefThreads = 8u;

    // A directory where all the tool executables are located
    String SysDir;
    // A path to script API header
    String ApiAshPath;
    // Game project's source directory
    String SrcDir;
    // Game project's document file (Game.agf by default)
    String SrcAgf;
    // If agsbuild owns temporary output directory (must delete on cleanup)
    bool OwnTempDir = false;
    // Temporary directory for any intermediate output
    String TempDir;
    // Final output directory for deploying game build
    String OutDir;
    // Should we recreate spitefile by importing sprites from source image files,
    // even if one already exists.
    bool ReimportSprites = false;
    // Should we reimport all audio clips
    bool ReimportAudio = false;
    // Delete intermediate files on successful completion
    bool Cleanup = false;
    // Max threads used for running tasks (does not include main program thread)
    uint32_t TaskThreads = DefThreads;
    bool Verbose = false;
    // Build mode (overrides game project settings)
    bool BuildDebug = false;
    bool BuildRelease = false;
};

struct GameOptions
{
    String Name;
    String FileName;
    int UniqueID = 0;
    DataUtil::SpriteCompression SpriteCompression = DataUtil::SpriteCompression::kSprCompress_Deflate;
    bool SpriteOptimizeStorage = true;
};

struct ScriptCompilerOptions
{
    String EditorVersion;
    String ApiVersion = "Highest";
    String CompatVersion = "Highest";
    bool EnforcePost262Scripting = true; // aka Object-oriented scripting
    bool EnforceNewStrings = true;
    bool EnforceNewAudio = true;
    bool OldDialogOptionsAPI = true;
    bool DebugBuild = false;
};

const uint32_t BuildOptions::MinThreads;
const uint32_t BuildOptions::MaxThreads;
const uint32_t BuildOptions::DefThreads;

String MakeAGSCCFlags(const ScriptCompilerOptions &opts)
{
    return String::FromFormat("--override-version %s -A %s -C %s -fforceobjectbasedscript=%s -fforcenewstrings=%s -fforcenewaudio=%s -foldcustomdialogopt=%s %s",
        opts.EditorVersion.GetCStr(),
        opts.ApiVersion.GetCStr(),
        opts.CompatVersion.GetCStr(),
        opts.EnforcePost262Scripting ? "1" : "0",
        opts.EnforceNewStrings ? "1" : "0",
        opts.EnforceNewAudio ? "1" : "0",
        opts.OldDialogOptionsAPI ? "1" : "0",
        opts.DebugBuild ? "-g" : ""
        );
}

String MakeSpriteImportFlags(const GameOptions &opts)
{
    int sflags = 0;
    const char *compress;
    switch (opts.SpriteCompression)
    {
    case DataUtil::SpriteCompression::kSprCompress_None: compress = "none"; break;
    case DataUtil::SpriteCompression::kSprCompress_RLE: compress = "rle"; break;
    case DataUtil::SpriteCompression::kSprCompress_LZW: compress = "lzw"; break;
    case DataUtil::SpriteCompression::kSprCompress_Deflate:
    default:
        compress = "deflate"; break;
    }
    sflags |= 0x1 * opts.SpriteOptimizeStorage;
    return String::FromFormat("-z %s -s 0x%x", compress, sflags);
}

HError BuildWithTaskManager(const BuildOptions &bopts)
{
    const String &sys_dir = bopts.SysDir;
    const String &src_dir = bopts.SrcDir;
    const String &api_ash = bopts.ApiAshPath;
    const String audiocache_dir = Path::ConcatPaths(src_dir, "AudioCache");
    const String speech_dir = Path::ConcatPaths(src_dir, "Speech");
    const String &src_agf = bopts.SrcAgf;
    const String &temp_dir = bopts.TempDir;
    const String &out_dir = bopts.OutDir;
    const char *verbose = bopts.Verbose ? "-v" : "";

    // Currently it's more convenient to read AGF lists and compilation-related options directly,
    // rather than trying to use agfexport for this.
    // TODO: support more compile options, such as script options, package splitting, attach to exe etc
    GameOptions game_opts;
    ScriptCompilerOptions agscc_opts;
    std::vector<DataUtil::AudioClipData> aclip_list;
    std::vector<String> custom_dirs;
    std::vector<int> font_list;
    std::vector<String> plugin_list;
    std::vector<String> room_list_crm;
    std::vector<String> scm_list;
    std::vector<String> scm_header_list;
    std::vector<String> tra_list;
    bool has_globalvar_script = false;
    {
        AGF::AGFReader reader;
        HError err = reader.Open(src_agf.GetCStr());
        if (!err)
            return new Error(String::FromFormat("Failed to open and/or read %s", src_agf.GetCStr()), err);

        DataUtil::GameSettings opts;
        AGF::ReadGameSettings(opts, reader.GetGameRoot());
        game_opts.FileName = opts.GameFileName;
        game_opts.Name = opts.GameName;
        game_opts.UniqueID = opts.UniqueID;

        agscc_opts.EditorVersion = reader.GetEditorVersion();
        agscc_opts.ApiVersion = opts.ScriptAPIVersion;
        agscc_opts.CompatVersion = opts.ScriptCompatLevel;
        agscc_opts.EnforcePost262Scripting = opts.EnforceObjectBasedScript;
        agscc_opts.EnforceNewAudio = opts.EnforceNewAudio;
        agscc_opts.EnforceNewStrings = opts.EnforceNewStrings;
        agscc_opts.OldDialogOptionsAPI = opts.UseOldCustomDialogOptionsAPI;
        agscc_opts.DebugBuild = (opts.DebugMode || bopts.BuildDebug) && (!bopts.BuildRelease);

        AGF::ReadAudioClips(aclip_list, reader.GetGameRoot());
        AGF::ReadCustomDataDirectories(custom_dirs, reader.GetGameRoot());
        AGF::ReadFontList(font_list, reader.GetGameRoot());
        AGF::ReadPluginList(plugin_list, reader.GetGameRoot());
        std::vector<std::pair<int, String>> room_list_with_desc;
        AGF::ReadRoomList(room_list_with_desc, reader.GetGameRoot());
        for (const auto &r : room_list_with_desc)
        {
            room_list_crm.push_back(String::FromFormat("room%d.crm", r.first));
        }
        AGF::ReadScriptList(scm_list, reader.GetGameRoot());
        AGF::ReadScriptHeaderList(scm_header_list, reader.GetGameRoot());
        AGF::ReadTranslationList(tra_list, reader.GetGameRoot());

        // FIXME: this is bit ugly, we only need to know if there will be a GlobalVariables script, is there a better way?
        std::vector<DataUtil::Variable> vars;
        AGF::ReadGlobalVariables(vars, reader.GetGameRoot());
        has_globalvar_script = !vars.empty();
    }

    //-----------------------------------------------------
    // Configure game building pipeline
    //-----------------------------------------------------

    // TODO: get number of threads from command line
    TaskManager taskmgr(Math::Clamp(bopts.TaskThreads, BuildOptions::MinThreads, BuildOptions::MaxThreads), verbose);
    // Lists of packed files from various locations (filenames only)
    // TODO: figure out a more efficient way to store these
    std::vector<String> pak_src_files;
    std::vector<String> pak_temp_files;
    std::vector<String> pak_src_audio_files;
    std::vector<String> pak_temp_audio_files;
    std::vector<String> avox_src_files;
    std::vector<String> avox_temp_files;
    // Extra files that may be created as output, but not packed nor deployed
    std::vector<String> clnup_temp_files;
    std::vector<String> clnup_avox_temp_files;
    // files that should be not packed but copied along with the game.ags
    std::vector<String> deploy_temp_files;
    // tasks to complete before packaging game files
    std::vector<TaskInput> pre_pack_tasks;
    // tasks to complete before packaging audio vox
    std::vector<TaskInput> pre_avox_tasks;
    // tasks to complete before packaging speech vox
    std::vector<TaskInput> pre_svox_tasks;
    // tasks to complete before deploying game files
    std::vector<TaskInput> pre_deploy_tasks;

    // Export all the necessary information
    {
        const String tool_agfexport = Path::ConcatPaths(sys_dir, ToolAgfExport);
        const String tool_dlgasc = Path::ConcatPaths(sys_dir, ToolDlgAsc);

        taskmgr.AddTask(std::make_unique<TaskPipedProcess>("autoash", &taskmgr,
            PipedProcessParams(tool_agfexport, String::FromFormat("autoash \"%s\" \"%s/_AutoGenerated.ash\" %s", src_agf.GetCStr(), temp_dir.GetCStr(), verbose))));
        taskmgr.AddTask(std::make_unique<TaskPipedProcess>("game-cfg", &taskmgr,
            PipedProcessParams(tool_agfexport, String::FromFormat("game-cfg \"%s\" \"%s/acsetup.cfg\" %s", src_agf.GetCStr(), temp_dir.GetCStr(), verbose))));
        // Always run "glvar" task, even if game has no global variables (no glvar scripts will be created in such case),
        // as there are other tasks down the line that have "glvar" in prerequisites, so it must complete with success.
        taskmgr.AddTask(std::make_unique<TaskPipedProcess>("glvar", &taskmgr,
            PipedProcessParams(tool_agfexport, String::FromFormat("glvar \"%s\" \"%s/_GlobalVariables.ash\" \"%s/_GlobalVariables.asc\" --no-empty %s", src_agf.GetCStr(), temp_dir.GetCStr(), temp_dir.GetCStr(), verbose))));
        taskmgr.AddTask(std::make_unique<TaskPipedProcess>("dlgasc", &taskmgr,
            PipedProcessParams(tool_dlgasc, String::FromFormat("\"%s\" \"%s/__DialogScripts.asc\" %s", src_agf.GetCStr(), temp_dir.GetCStr(), verbose))));

        deploy_temp_files.push_back("acsetup.cfg");
        clnup_temp_files.push_back("_AutoGenerated.ash");
        clnup_temp_files.push_back("_GlobalVariables.ash");
        clnup_temp_files.push_back("_GlobalVariables.asc");
        clnup_temp_files.push_back("__DialogScripts.asc");
        pre_deploy_tasks.push_back({"game-cfg"});
    }

    // Build game28.dta
    {
        const String tool_agf2dta = Path::ConcatPaths(sys_dir, ToolAgf2Dta);
        taskmgr.AddTask(std::make_unique<TaskPipedProcess>("agf2dta", &taskmgr,
            PipedProcessParams(tool_agf2dta, String::FromFormat("\"%s\" \"%s/game28.dta\" %s", src_agf.GetCStr(), temp_dir.GetCStr(), verbose))));
        pak_temp_files.push_back("game28.dta");
        pre_pack_tasks.push_back({"agf2dta"});
    }

    // Compile game scripts
    String all_script_headers;
    std::vector<String> scom_modules_list; // compiled scripts that must be listed in ScriptModules.lst
    {
        const String tool_agscc = Path::ConcatPaths(sys_dir, ScriptCompiler);
        String base_headers = String::FromFormat("%s" AGSCC_H_SEP "%s/%s", api_ash.GetCStr(), temp_dir.GetCStr(), ScriptAutoHeader);
        std::vector<String> scom_obj;
        std::vector<String> scom_tasks;

        if (has_globalvar_script)
        {
            base_headers.AppendFmt(AGSCC_H_SEP "%s/%s", temp_dir.GetCStr(), ScriptGlvarHeader);
            const String task_name = String::FromFormat("agscc:%s", ScriptGlvarScript);
            taskmgr.AddTask(std::unique_ptr<Task>(new TaskPipedProcess(task_name, &taskmgr,
                PipedProcessParams(tool_agscc, String::FromFormat("\"%s/%s\" -H \"%s\" -o \"%s/%s\" %s", temp_dir.GetCStr(), ScriptGlvarScript, base_headers.GetCStr(), temp_dir.GetCStr(), ScriptGlvarScom,
                    MakeAGSCCFlags(agscc_opts).GetCStr())),
                {{"autoash"}, {"glvar"}})));
            scom_obj.push_back(ScriptGlvarScom);
            scom_tasks.push_back(task_name);
        }

        {
            String headers = base_headers;
            for (size_t sm = 0; sm < scm_list.size(); ++sm)
            {
                if (sm < scm_header_list.size())
                    headers.AppendFmt(AGSCC_H_SEP "%s/%s", src_dir.GetCStr(), scm_header_list[sm].GetCStr());
                const String scm_obj = Path::ReplaceExtension(scm_list[sm], "o");
                const String task_name = String::FromFormat("agscc:%s", scm_list[sm].GetCStr());
                taskmgr.AddTask(std::unique_ptr<Task>(new TaskPipedProcess(task_name, &taskmgr,
                    PipedProcessParams(tool_agscc, String::FromFormat("\"%s/%s\" -H \"%s\" -o \"%s/%s\" %s", src_dir.GetCStr(), scm_list[sm].GetCStr(), headers.GetCStr(), temp_dir.GetCStr(), scm_obj.GetCStr(),
                        MakeAGSCCFlags(agscc_opts).GetCStr())),
                    {{"autoash"}, {"glvar"}})));
                scom_obj.push_back(scm_obj);
                scom_tasks.push_back(task_name);
            }
            all_script_headers = headers;
        }
        // TODO: perhaps write all, and let engine filter global script (and other special scripts) out?
        for (const auto scm : scom_obj)
            if (scm != "GlobalScript.o")
                scom_modules_list.push_back(scm);

        {
            // Dialog script uses all the accumulated script module headers
            const String task_name = String::FromFormat("agscc:%s", ScriptDialogScript);
            taskmgr.AddTask(std::unique_ptr<Task>(new TaskPipedProcess(task_name, &taskmgr,
                PipedProcessParams(tool_agscc, String::FromFormat("\"%s/%s\" -H \"%s\" -o \"%s/%s\" %s", temp_dir.GetCStr(), ScriptDialogScript, all_script_headers.GetCStr(), temp_dir.GetCStr(), ScriptDialogScom,
                    MakeAGSCCFlags(agscc_opts).GetCStr())),
                {{"autoash"}, {"glvar"}, {"dlgasc"}})));
            // NOTE: dialog script is special and is not added to the "script modules" list
            scom_obj.push_back(ScriptDialogScom);
            scom_tasks.push_back(task_name);
        }

        std::copy(scom_obj.begin(), scom_obj.end(), std::back_inserter(pak_temp_files));
        std::copy(scom_tasks.begin(), scom_tasks.end(), std::back_inserter(pre_pack_tasks));
    }

    // Compile room scripts and prepare output room CRM files (without embedded scripts)
    {
        const String tool_crmpak = Path::ConcatPaths(sys_dir, ToolCrmPak);
        const String tool_agscc = Path::ConcatPaths(sys_dir, ScriptCompiler);

        // Copy room files to temp dir, because we need to modify them
        std::vector<std::pair<String, String>> copy_rooms;
        for (const auto &r : room_list_crm)
            copy_rooms.push_back(std::make_pair(Path::ConcatPaths(src_dir, r), Path::ConcatPaths(temp_dir, r)));
        taskmgr.AddTask(std::unique_ptr<Task>(new TaskMoveFiles("copy-rooms", &taskmgr, copy_rooms, FileMoveOp::Copy, false /* no skip */)));

        // Add tasks for each room
        for (const auto &r : room_list_crm)
        {
            const String room_asc = Path::ReplaceExtension(r, "asc");
            const String room_ash = Path::ReplaceExtension(r, "ash");
            const String room_scom = Path::ReplaceExtension(r, "o");
            const String task_cut_script = String::FromFormat("crmpak:%s:cut-old-scripts", r.GetCStr());
            const String task_ash = String::FromFormat("crmpak:%s:ash", r.GetCStr());
            // Cut old scripts (we may skip this if we decide to import new scripts into room file instead)
            taskmgr.AddTask(std::unique_ptr<Task>(new TaskPipedProcess(task_cut_script, &taskmgr,
                PipedProcessParams(tool_crmpak, String::FromFormat("\"%s/%s\" -x script %s", temp_dir.GetCStr(), r.GetCStr(), verbose)),
                {{"copy-rooms"}})));
            // Export room script header
            taskmgr.AddTask(std::unique_ptr<Task>(new TaskPipedProcess(task_ash, &taskmgr,
                PipedProcessParams(tool_crmpak, String::FromFormat("\"%s/%s\" -e ash \"%s/%s\" %s", temp_dir.GetCStr(), r.GetCStr(), temp_dir.GetCStr(), room_ash.GetCStr(), verbose)),
                {{"copy-rooms"}, {task_cut_script}})));
            // Compile room script
            const String room_headers = String::FromFormat("%s" AGSCC_H_SEP "%s/%s", all_script_headers.GetCStr(), temp_dir.GetCStr(), room_ash.GetCStr());
            const String room_agscc_task = String::FromFormat("agscc:%s", room_asc.GetCStr());
            taskmgr.AddTask(std::unique_ptr<Task>(new TaskPipedProcess(room_agscc_task, &taskmgr,
                PipedProcessParams(tool_agscc, String::FromFormat("\"%s/%s\" -H \"%s\" -o \"%s/%s\" %s", src_dir.GetCStr(), room_asc.GetCStr(), room_headers.GetCStr(), temp_dir.GetCStr(), room_scom.GetCStr(),
                    MakeAGSCCFlags(agscc_opts).GetCStr())),
                {{"autoash"}, {"glvar"}, {task_cut_script}, {task_ash}})));

            pak_temp_files.push_back(r);
            pak_temp_files.push_back(room_scom);
            clnup_temp_files.push_back(room_ash);
            pre_pack_tasks.push_back(room_agscc_task);
        }
    }

    // Write ScriptModules.lst
    {
        taskmgr.AddTask(std::unique_ptr<Task>(new TaskWriteStringList("write-script-list", &taskmgr,
            Path::ConcatPaths(temp_dir, "ScriptModules.lst"), scom_modules_list)));
        pak_temp_files.push_back("ScriptModules.lst");
        pre_pack_tasks.push_back({"write-script-list"});
    }

    // Compile translations
    {
        const String tool_trac = Path::ConcatPaths(sys_dir, ToolTrac);
        for (const auto &tra : tra_list)
        {
            const String task_name = String::FromFormat("trac:%s", tra.GetCStr());
            const String out_trafile = String::FromFormat("%s.tra", tra.GetCStr());
            taskmgr.AddTask(std::unique_ptr<Task>(new TaskPipedProcess(task_name, &taskmgr,
                PipedProcessParams(tool_trac, String::FromFormat("\"%s/%s.trs\" \"%s/%s\" --gamename \"%s\" --uniqueid %d %s",
                    src_dir.GetCStr(), tra.GetCStr(), temp_dir.GetCStr(), out_trafile.GetCStr(), game_opts.Name.GetCStr(), game_opts.UniqueID, verbose)))));
            deploy_temp_files.push_back(out_trafile);
            pre_deploy_tasks.push_back(task_name);
        }
    }

    // Rebuild sprite file if necessary / possible;
    // collect either one in source dir, or the one we built in temp dir to the list of packed files
    {
        const String src_spritefile = Path::ConcatPaths(src_dir, "acsprset.spr");
        const String src_spriteindexfile = Path::ConcatPaths(src_dir, "sprindex.dat");
        if (bopts.ReimportSprites || !File::IsFile(src_spritefile))
        {
            // TODO: get sprite packaging options from game settings
            const String tool_spriteimport = Path::ConcatPaths(sys_dir, ToolSpriteImport);
            taskmgr.AddTask(std::unique_ptr<Task>(new TaskPipedProcess("spriteimport", &taskmgr,
                PipedProcessParams(tool_spriteimport, String::FromFormat("-c \"%s\" \"%s/acsprset.spr\" -n \"%s/sprindex.dat\" %s %s", src_agf.GetCStr(), temp_dir.GetCStr(), temp_dir.GetCStr(),
                    MakeSpriteImportFlags(game_opts).GetCStr(), verbose)))));
            pak_temp_files.push_back("acsprset.spr");
            pak_temp_files.push_back("sprindex.dat");
            pre_pack_tasks.push_back({"spriteimport"});
        }
        else
        {
            pak_src_files.push_back("acsprset.spr");
            if (File::IsFile(src_spriteindexfile))
                pak_src_files.push_back("sprindex.dat");
        }
    }

    // Reimport audio clips, if necessary / possible;
    // collect either ones in source dir, or the ones we import onto the temp dir to the list of packed files
    if (aclip_list.size() > 0)
    {
        // Create temp AudioCache dir always, because we use it to make hardlinks, write include file and package audio files
        const String temp_audio_dir = Path::ConcatPaths(bopts.TempDir, "AudioCache");
        if (!Directory::CreateDirectory(temp_audio_dir))
            return new Error(String::FromFormat("Error: failed to create temporary audio cache directory '%s'", temp_audio_dir.GetCStr()));

        std::vector<DataUtil::AudioClipData> src_clips;
        std::vector<DataUtil::AudioClipData> temp_clips;
        for (const auto &aclip : aclip_list)
        {
            // TODO: check file times here! even if reimport audio is on, dont copy to temp if can take up-to-date file from src
            if (bopts.ReimportAudio || !File::IsFile(Path::ConcatPaths(audiocache_dir, aclip.CacheFileName)))
                temp_clips.push_back(aclip);
            else
                src_clips.push_back(aclip);
        }

        if (temp_clips.size() > 0)
        {
            std::vector<std::pair<String, String>> copy_aclips;
            for (const auto &aclip : temp_clips)
            {
                const String source_fn = Path::IsRelativePath(aclip.SourceFileName) ? Path::ConcatPaths(src_dir, aclip.SourceFileName) : aclip.SourceFileName;
                copy_aclips.push_back(std::make_pair(source_fn, Path::ConcatPaths(temp_audio_dir, aclip.CacheFileName)));
                if (aclip.BundlingType == DataUtil::kAudioBundling_InMainData)
                    pak_temp_audio_files.push_back(aclip.CacheFileName);
                else
                    avox_temp_files.push_back(aclip.CacheFileName);
            }
            taskmgr.AddTask(std::unique_ptr<Task>(new TaskMoveFiles("import-audio", &taskmgr, copy_aclips,
                FileMoveOp::Hardlink, true /* skip non-existing */, {})));
            pre_pack_tasks.push_back({"import-audio"});
            pre_avox_tasks.push_back({"import-audio"});
        }

        for (const auto &aclip : src_clips)
        {
            if (aclip.BundlingType == DataUtil::kAudioBundling_InMainData)
                pak_src_audio_files.push_back(aclip.CacheFileName);
            else
                avox_src_files.push_back(aclip.CacheFileName);
        }
    }

    // Collect other necessary files from the source directory
    {
        // Add font files
        for (const auto &fnt : font_list)
        {
            const String ttf_file = String::FromFormat("agsfnt%d.ttf", fnt);
            const String wfn_file = String::FromFormat("agsfnt%d.wfn", fnt);
            if (File::IsFile(Path::ConcatPaths(src_dir, ttf_file)))
                pak_src_files.push_back(ttf_file);
            if (File::IsFile(Path::ConcatPaths(src_dir, wfn_file)))
                pak_src_files.push_back(wfn_file);
        }

        // Gather list of valid custom directories
        for (const auto &cd : custom_dirs)
        {
            // Don't allow absolute paths
            if (!Path::IsRelativePath(cd))
                continue;

            const String full_cd = Path::ConcatPaths(src_dir, cd);
            // Don't let a custom path equal to the source dir
            if (Path::ComparePaths(src_dir, full_cd) == 0)
                continue;

            // Don't allow paths to outside of the source dir
            if (!Path::IsSameOrSubDir(src_dir, full_cd))
                continue;

            // TODO: // don't allow paths that match or inside restricted folders,
            // or folders that were already used to make a list of assets

            // Create same custom directory inside temporary dir
            const String temp_cd = Path::ConcatPaths(temp_dir, cd);
            if (!Directory::CreateDirectory(temp_cd))
                return new Error(String::FromFormat("Error: failed to create temporary custom data directory '%s'", temp_cd.GetCStr()));

            for (FindFile ff = FindFile::Open(full_cd, "*", true, false); !ff.AtEnd(); ff.Next())
                pak_src_files.push_back(Path::ConcatPaths(cd, ff.Current()));
        }
    }

    // Pack selected files into game.ags
    {
        const String tool_agspak = Path::ConcatPaths(sys_dir, ToolAgsPak);
        const String audio_cache_dir = Path::ConcatPaths(src_dir, "AudioCache");
        const String audio_cache_temp_dir = Path::ConcatPaths(temp_dir, "AudioCache");

        std::vector<TaskInput> final_pre_pack_tasks = pre_pack_tasks;

        // Hardlink all packaged files from src dir into the temp dir,
        // this is done to let use patterns file in the single location
        std::vector<std::pair<String, String>> hl_files;
        for (const auto &f : pak_src_files)
            hl_files.push_back(std::make_pair(Path::ConcatPaths(src_dir, f), Path::ConcatPaths(temp_dir, f)));
        for (const auto &f : pak_src_audio_files)
            hl_files.push_back(std::make_pair(Path::ConcatPaths(audio_cache_dir, f), Path::ConcatPaths(audio_cache_temp_dir, f)));
        taskmgr.AddTask(std::unique_ptr<Task>(new TaskMoveFiles("hardlink-src", &taskmgr, hl_files, FileMoveOp::Hardlink, false /* no skip */, pre_pack_tasks)));
        std::copy(pak_src_files.begin(), pak_src_files.end(), std::back_inserter(pak_temp_files));
        std::copy(pak_src_audio_files.begin(), pak_src_audio_files.end(), std::back_inserter(pak_temp_audio_files));
        final_pre_pack_tasks.push_back({"hardlink-src"});

        // Write patterns file for main data packed into game.ags
        std::vector<String> file_pat;
        for (const auto &f : pak_temp_files)
            file_pat.push_back(f);
        const String include_file = "agspak-include.files";
        taskmgr.AddTask(std::unique_ptr<Task>(new TaskWriteStringList("write-agspak-includefile:root", &taskmgr,
            Path::ConcatPaths(temp_dir, include_file), file_pat, pre_pack_tasks)));
        clnup_temp_files.push_back(include_file);
        final_pre_pack_tasks.push_back({"write-agspak-includefile:root"});

        // Write patterns file for the audio packed into game.ags (if necessary)
        if (pak_temp_audio_files.size())
        {
            file_pat.clear();
            for (const auto &f : pak_temp_audio_files)
                file_pat.push_back(f);
            taskmgr.AddTask(std::unique_ptr<Task>(new TaskWriteStringList("write-agspak-includefile:audiocache", &taskmgr,
                Path::ConcatPaths(audio_cache_temp_dir, include_file), file_pat, pre_pack_tasks)));
            clnup_avox_temp_files.push_back(include_file);
            final_pre_pack_tasks.push_back({"write-agspak-includefile:audiocache"});
        }

        const String game_pack_name = String::FromFormat("%s.ags", game_opts.FileName.GetCStr());
        taskmgr.AddTask(std::unique_ptr<Task>(new TaskPipedProcess("agspak:game.ags", &taskmgr,
            PipedProcessParams(tool_agspak, String::FromFormat("-c \"%s/%s\" \"%s\" -r -D \"%s\" -f \"%s\" --replace-dup %s",
                temp_dir.GetCStr(), // output pak dir
                game_pack_name.GetCStr(), // game.ags name
                temp_dir.GetCStr(), // temp output dir
                audio_cache_temp_dir.GetCStr(), // temp audio cache (for audio clips embedded into game.ags)
                include_file.GetCStr(), // patterns file
                verbose
            )), final_pre_pack_tasks)));
        
        deploy_temp_files.push_back(game_pack_name);
        pre_deploy_tasks.push_back({"agspak:game.ags"});
    }

    // Pack selected files into audio.vox
    if (avox_src_files.size() > 0 || avox_temp_files.size() > 0)
    {
        const String tool_agspak = Path::ConcatPaths(sys_dir, ToolAgsPak);
        const String audio_cache_dir = Path::ConcatPaths(src_dir, "AudioCache");
        const String audio_cache_temp_dir = Path::ConcatPaths(temp_dir, "AudioCache");

        std::vector<TaskInput> final_pre_avox_tasks = pre_avox_tasks;

        // Hardlink all packaged files from src dir into the temp dir,
        // this is done to let use patterns file in the single location
        std::vector<std::pair<String, String>> hl_files;
        for (const auto &f : avox_src_files)
            hl_files.push_back(std::make_pair(Path::ConcatPaths(audio_cache_dir, f), Path::ConcatPaths(audio_cache_temp_dir, f)));
        taskmgr.AddTask(std::unique_ptr<Task>(new TaskMoveFiles("hardlink-avox-src", &taskmgr, hl_files, FileMoveOp::Hardlink, false /* no skip */, pre_avox_tasks)));
        std::copy(avox_src_files.begin(), avox_src_files.end(), std::back_inserter(avox_temp_files));
        final_pre_avox_tasks.push_back({"hardlink-avox-src"});

        // Write patterns file
        std::vector<String> file_pat;
        for (const auto &f : avox_temp_files)
            file_pat.push_back(f);

        const String include_file = "avox-include.files";
        taskmgr.AddTask(std::unique_ptr<Task>(new TaskWriteStringList("write-avox-includefile", &taskmgr,
            Path::ConcatPaths(audio_cache_temp_dir, include_file), file_pat, pre_avox_tasks)));
        clnup_avox_temp_files.push_back(include_file);
        final_pre_avox_tasks.push_back({"write-avox-includefile"});

        taskmgr.AddTask(std::unique_ptr<Task>(new TaskPipedProcess("agspak:audio.vox", &taskmgr,
            PipedProcessParams(tool_agspak, String::FromFormat("-c \"%s/audio.vox\" \"%s\" -f \"%s\" --replace-dup %s",
                temp_dir.GetCStr(), // output pak dir
                audio_cache_temp_dir.GetCStr(), // temp output dir
                include_file.GetCStr(), // file match filter
                verbose
            )), final_pre_avox_tasks)));

        std::copy(avox_src_files.begin(), avox_src_files.end(), std::back_inserter(clnup_avox_temp_files));
        deploy_temp_files.push_back("audio.vox");
        pre_deploy_tasks.push_back({"agspak:audio.vox"});
    }

    // TODO: compile lipsync data from Pamela/Papagayo sources
    // would need a separate tool for that!

    // Pack selected files into speech.vox
    // TODO: restrict voice files to the naming format (`NNNNXXXX.ext` old format and `name.X.ext` new format).
    // FIXME: use speech_file_filter in HasAnyFiles, but must make it support multi-pattern
    {
        const String tool_agspak = Path::ConcatPaths(sys_dir, ToolAgsPak);
        const String speech_file_filter = "*.mp3,*.ogg,*.wav" // default voice-over formats
            ",syncdata.dat"; // compiled lipsync output
        std::vector<String> sub_dirs = { {} /* placeholder for parent dir */};
        Directory::GetDirs(speech_dir, sub_dirs);
        for (const auto &sp_dir : sub_dirs)
        {
            const String dir_path = Path::ConcatPaths(speech_dir, sp_dir);
            if (Directory::HasAnyFiles(dir_path))
            {
                const String pak_name = sp_dir.IsEmpty() ? "speech.vox" : String::FromFormat("sp_%s.vox", sp_dir.GetCStr());
                const String task_name = String::FromFormat("agspak:%s", pak_name.GetCStr());
                taskmgr.AddTask(std::unique_ptr<Task>(new TaskPipedProcess(task_name, &taskmgr,
                    PipedProcessParams(tool_agspak, String::FromFormat("-c \"%s/%s\" \"%s\" \"%s\" --replace-dup %s",
                        temp_dir.GetCStr(), // output pak dir
                        pak_name.GetCStr(),
                        dir_path.GetCStr(), // speech input dir
                        speech_file_filter.GetCStr(), // file match filter
                        verbose
                    )), pre_svox_tasks)));

                deploy_temp_files.push_back(pak_name);
                pre_deploy_tasks.push_back({task_name});
            }
        }
    }

    // Move final files to the destination dir
    {
        std::vector<std::pair<String, String>> deploy_data;
        for (const auto &f : deploy_temp_files)
            deploy_data.push_back(std::make_pair(Path::ConcatPaths(temp_dir, f), Path::ConcatPaths(out_dir, f)));
        taskmgr.AddTask(std::unique_ptr<Task>(new TaskMoveFiles("deploy-data", &taskmgr, deploy_data,
            FileMoveOp::Move, false /* no skip */, pre_deploy_tasks)));
    }

    // Cleanup on success
    if (bopts.Cleanup)
    {
        std::vector<String> cleanup_files;
        for (const auto &f : pak_temp_files)
            cleanup_files.push_back(Path::ConcatPaths(temp_dir, f));
        for (const auto &f : deploy_temp_files)
            cleanup_files.push_back(Path::ConcatPaths(temp_dir, f));
        for (const auto &f : clnup_temp_files)
            cleanup_files.push_back(Path::ConcatPaths(temp_dir, f));
        const String &temp_audio_dir = Path::ConcatPaths(temp_dir, "AudioCache");
        for (const auto &f : pak_temp_audio_files)
            cleanup_files.push_back(Path::ConcatPaths(temp_audio_dir, f));
        for (const auto &f : avox_temp_files)
            cleanup_files.push_back(Path::ConcatPaths(temp_audio_dir, f));
        for (const auto &f : clnup_avox_temp_files)
            cleanup_files.push_back(Path::ConcatPaths(temp_audio_dir, f));
        taskmgr.AddTask(std::unique_ptr<Task>(new TaskDeleteFiles("cleanup-temp", &taskmgr, cleanup_files,
            {{"deploy-data"}})));
    }

    HError err = taskmgr.RunAll();
    if (err)
        printf("\n\nSuccessfully compiled \"%s\" game files in %s\n", game_opts.Name.GetCStr(), bopts.OutDir.GetCStr());
    return err;
}


const char *HELP_STRING = ""
//--------------------------------------------------------------------------------|
"agsbuild v0.1.0 - AGS game project build tool\n"
"Copyright (c) 2026 AGS Team and contributors\n"
"Usage: agsbuild <input-game.agf> <out-dir> [<OPTIONS>]\n"
"\n"
"Options:\n"
"  --api-ash <path>       a path to the script API header. If not provided,\n"
"                         agsbuild will look for the 'agsdefns.sh' file inside the\n"
"                         system (tools) directory.\n"
"  --build-debug          builds the project in debug mode (override).\n"
"  --build-release        builds the project in release mode (override).\n"
"  -c, --cleanup          deletes intermediate output on successful completion.\n"
"  --import-audio         generate a new audio cache, importing audio files from\n"
"                         the source files, according to game.agf specs.\n"
"  --import-sprites       create a new sprite pack, importing sprites from the\n"
"                         source image files, according to game.agf specs.\n"
"                         Requires a presence of spriteimport tool.\n"
"  -s, --sys-dir <path>   a path to the system directory, where all the tools are\n"
"                         located. If not provided, agsbuild will assume it is\n"
"                         the same directory where it's located.\n"
"  -t, --temp-dir <path>  a path to the intermediate (temporary) outout directory.\n"
"                         If not provided, agsbuild will try creating one as a\n"
"                         subdirectory inside output directory.\n"
"  -p, --threads <N>      limit task threads to this number (default: 8);\n"
"                         note that tasks may spawn new processes, executing other\n"
"                         tools.\n"
"  -v, --verbose          print operation details (also affects spawned processes)\n"
;

int main(int argc, char *argv[])
{
    CmdLineOpts::ParseResult cmdargs = CmdLineOpts::Parse(argc, argv,
        {"--api-ash", "-s", "--sys-dir", "-t", "--temp-dir", "-p", "--threads"});
    if (cmdargs.HelpRequested)
    {
        printf("%s\n", HELP_STRING);
        return 0; // display help and bail out
    }
    
    if (cmdargs.PosArgs.size() < 2)
    {
        printf("Error: not enough arguments\n");
        printf("%s\n", HELP_STRING);
        return -1;
    }

    BuildOptions bopts;
    bopts.SrcAgf = Path::MakeAbsolutePath(cmdargs.PosArgs[0]);
    bopts.OutDir = Path::MakeAbsolutePath(cmdargs.PosArgs[1]);
    bopts.SrcDir = Path::GetParent(Path::MakeAbsolutePath(bopts.SrcAgf));
    bopts.ReimportAudio = cmdargs.Opt.count("--import-audio") > 0;
    bopts.ReimportSprites = cmdargs.Opt.count("--import-sprites") > 0;
    bopts.Cleanup = cmdargs.Opt.count("-c") > 0 || cmdargs.Opt.count("--cleanup") > 0;
    bopts.Verbose = cmdargs.Opt.count("-v") > 0 || cmdargs.Opt.count("--verbose") > 0;
    bopts.BuildDebug = cmdargs.Opt.count("--build-debug") > 0;
    bopts.BuildRelease = cmdargs.Opt.count("--build-release") > 0;
    for (const auto &opt : cmdargs.OptWithValue)
    {
        if (opt.first == "--api-ash")
            bopts.ApiAshPath = Path::MakeAbsolutePath(opt.second);
        if (opt.first == "-s" || opt.first == "--sys-dir")
            bopts.SysDir = Path::MakeAbsolutePath(opt.second);
        if (opt.first == "-t" || opt.first == "--temp-dir")
        {
            bopts.OwnTempDir = false;
            bopts.TempDir = Path::MakeAbsolutePath(opt.second);
        }
        if (opt.first == "-p" || opt.first == "--threads")
            bopts.TaskThreads = StrUtil::StringToInt(opt.second);
    }

    if (bopts.SysDir.IsEmpty())
        bopts.SysDir = Path::GetParent(File::GetThisExePath());
    if (bopts.ApiAshPath.IsEmpty())
        bopts.ApiAshPath = Path::ConcatPaths(bopts.SysDir, ScriptAPIHeader);
    if (bopts.TempDir.IsEmpty())
    {
        bopts.TempDir = Path::ConcatPaths(bopts.OutDir, "_temp");
        bopts.OwnTempDir = true;
    }

    printf("System dir: %s\n", bopts.SysDir.GetCStr());
    printf("Script API header: %s\n", bopts.ApiAshPath.GetCStr());
    printf("Project file: %s\n", bopts.SrcAgf.GetCStr());
    printf("Project dir: %s\n", bopts.SrcDir.GetCStr());
    printf("Output dir: %s\n", bopts.OutDir.GetCStr());
    printf("Temp dir: %s\n\n", bopts.TempDir.GetCStr());

    //-------------------------------------------------------------------------
    // Preliminary checks
    //-------------------------------------------------------------------------
    if (!File::IsFile(bopts.SrcAgf))
    {
        printf("Error: input project file '%s' not found or not a valid file", bopts.SrcAgf.GetCStr());
        return -1;
    }
    if (!File::IsDirectory(bopts.SrcDir))
    {
        printf("Error: input project directory '%s' not found or not a valid directory", bopts.SrcDir.GetCStr());
        return -1;
    }
    if (!File::IsDirectory(bopts.OutDir))
    {
        printf("Error: output directory '%s' not found or not a valid directory", bopts.OutDir.GetCStr());
        return -1;
    }

    //-------------------------------------------------------------------------
    // Prepare
    //-------------------------------------------------------------------------
    if (bopts.OwnTempDir && !Directory::CreateDirectory(bopts.TempDir))
    {
        printf("Error: failed to create intermediate output directory '%s'", bopts.TempDir.GetCStr());
        return -1;
    }

    HError err = BuildWithTaskManager(bopts);

    //-------------------------------------------------------------------------
    // Cleanup
    //-------------------------------------------------------------------------
    if (err)
    {
        if (bopts.OwnTempDir)
            Directory::DeleteDirectory(bopts.TempDir);
    }

    if (err)
        printf("Done.\n");
    else
        printf("%s\n", err->FullMessage().GetCStr());
    return err ? 0 : -1;
}
