//=============================================================================
//
// Adventure Game Studio (AGS)
//
// Copyright (C) 1999-2011 Chris Jones and 2011-2026 various contributors
// The full list of copyright holders can be found in the Copyright.txt
// file, which is part of this source code distribution.
//
// The AGS source code is provided under the Artistic License 2.0.
// A copy of this license can be found in the file License.txt and at
// https://opensource.org/license/artistic-2-0/
//
//=============================================================================
// 
// AGS game build utility.
// Uses a collection of AGS cli tools, compiles and builds the generic game
// package, using AGS game project and miscelaneous project files as input.
// 
//=============================================================================
#include <cstdio>
#include "platform/platform.h"
#if (AGS_PLATFORM_OS_WINDOWS)
#include "platform/windows/windows.h"
#endif
#include "data/agfreader.h"
#include "util/cmdlineopts.h"
#include "util/directory.h"
#include "util/file.h"
#include "util/path.h"
#include "util/string_utils.h"
#include "util/textstreamreader.h"
#include "util/textstreamwriter.h"
#include "pipedprocess.h"
#include "taskmanager.h"

using namespace AGS;
using namespace AGS::Common;

const char *ToolAgfExport       = "agfexport";
const char *ToolAgf2Dta         = "agf2dta";
const char *ToolDlgAsc          = "agf2dlgasc";
const char *ToolAgsPak          = "agspak";
const char *ToolCrmPak          = "crmpak";
const char *ToolTrac            = "trac";
const char *ToolSpriteImport    = "spriteimport";
const char *ScriptCompiler      = "agscc";
const char *ScriptAPIHeader     = "agsdefns.sh";
const char *ScriptAutoHeader    = "_AutoGenerated.ash";
const char *ScriptGlvarHeader   = "_GlobalVariables.ash";
const char *ScriptGlvarScript   = "_GlobalVariables.asc";
const char *ScriptGlvarScom     = "_GlobalVariables.o";
const char *ScriptDialogScript  = "__DialogScripts.asc";
const char *ScriptDialogScom    = "__DialogScripts.o";


using namespace AGSBuild;

struct BuildOptions
{
    static const uint32_t MinThreads = 1u;
    static const uint32_t MaxThreads = 32u;
    static const uint32_t DefThreads = 8u;

    // A directory where all the tool executables are located
    String SysDir;
    // Game project's source directory
    String SrcDir;
    // Game project's document file (Game.agf by default)
    String SrcAgf;
    // Temporary directory for any intermediate output
    String TempDir;
    // Final output directory for deploying game build
    String OutDir;
    // Should we recreate spitefile by importing sprites from source image files,
    // even if one already exists.
    bool ReimportSprites = false;
    // Should we reimport all audio clips
    bool ReimportAudio = false;
    // Max threads used for running tasks (does not include main program thread)
    uint32_t TaskThreads = DefThreads;
    bool Verbose = false;
};

HError BuildWithTaskManager(const BuildOptions &bopts)
{
    const String &sys_dir = bopts.SysDir;
    const String &src_dir = bopts.SrcDir;
    const String audiocache_dir = Path::ConcatPaths(src_dir, "AudioCache");
    const String speech_dir = Path::ConcatPaths(src_dir, "Speech");
    const String &src_agf = bopts.SrcAgf;
    const String &temp_dir = bopts.TempDir;
    const String &out_dir = bopts.OutDir;
    const char *verbose = bopts.Verbose ? "-v" : "";

    // Currently it's more convenient to read AGF lists and compilation-related options directly,
    // rather than trying to use agfexport for this.
    // TODO: support more compile options, such as script options, package splitting, attach to exe etc
    String game_file_name;
    std::vector<DataUtil::AudioClipData> aclip_list;
    std::vector<String> custom_dirs;
    std::vector<int> font_list;
    std::vector<String> plugin_list;
    std::vector<String> room_list_crm;
    std::vector<String> scm_list;
    std::vector<String> scm_header_list;
    std::vector<String> tra_list;
    bool has_globalvar_script = false;
    {
        AGF::AGFReader reader;
        HError err = reader.Open(src_agf.GetCStr());
        if (!err)
            return new Error(String::FromFormat("Failed to open and/or read %s", src_agf.GetCStr()), err);

        DataUtil::GameSettings opts;
        AGF::ReadGameSettings(opts, reader.GetGameRoot());
        game_file_name = opts.GameFileName;

        AGF::ReadAudioClips(aclip_list, reader.GetGameRoot());
        AGF::ReadCustomDataDirectories(custom_dirs, reader.GetGameRoot());
        AGF::ReadFontList(font_list, reader.GetGameRoot());
        AGF::ReadPluginList(plugin_list, reader.GetGameRoot());
        std::vector<std::pair<int, String>> room_list_with_desc;
        AGF::ReadRoomList(room_list_with_desc, reader.GetGameRoot());
        for (const auto &r : room_list_with_desc)
        {
            room_list_crm.push_back(String::FromFormat("room%d.crm", r.first));
        }
        AGF::ReadScriptList(scm_list, reader.GetGameRoot());
        AGF::ReadScriptHeaderList(scm_header_list, reader.GetGameRoot());
        AGF::ReadTranslationList(tra_list, reader.GetGameRoot());

        // FIXME: this is bit ugly, we only need to know if there will be a GlobalVariables script, is there a better way?
        std::vector<DataUtil::Variable> vars;
        AGF::ReadGlobalVariables(vars, reader.GetGameRoot());
        has_globalvar_script = !vars.empty();
    }

    //-----------------------------------------------------
    // Configure game building pipeline
    //-----------------------------------------------------

    // TODO: get number of threads from command line
    TaskManager taskmgr(Math::Clamp(bopts.TaskThreads, BuildOptions::MinThreads, BuildOptions::MaxThreads));
    std::vector<String> pak_src_files;
    std::vector<String> pak_custom_dirs;
    std::vector<String> pak_temp_files;
    std::vector<String> avox_src_files;
    std::vector<String> avox_temp_files;
    // files that should be not packed but copied along with the game.ags
    std::vector<String> deploy_temp_files;
    // tasks to complete before packaging game files
    std::vector<TaskInput> pre_pack_tasks;
    // tasks to complete before deploying game files
    std::vector<TaskInput> pre_deploy_tasks;

    // Export all the necessary information
    {
        const String tool_agfexport = Path::ConcatPaths(sys_dir, ToolAgfExport);
        const String tool_dlgasc = Path::ConcatPaths(sys_dir, ToolDlgAsc);

        taskmgr.AddTask(std::make_unique<TaskPipedProcess>("autoash", &taskmgr,
            PipedProcessParams(tool_agfexport, String::FromFormat("autoash %s %s/_AutoGenerated.ash %s", src_agf.GetCStr(), temp_dir.GetCStr(), verbose))));
        taskmgr.AddTask(std::make_unique<TaskPipedProcess>("game-cfg", &taskmgr,
            PipedProcessParams(tool_agfexport, String::FromFormat("game-cfg %s %s/acsetup.cfg %s", src_agf.GetCStr(), temp_dir.GetCStr(), verbose))));
        // Always run "glvar" task, even if game has no global variables (no glvar scripts will be created in such case),
        // as there are other tasks down the line that have "glvar" in prerequisites, so it must complete with success.
        taskmgr.AddTask(std::make_unique<TaskPipedProcess>("glvar", &taskmgr,
            PipedProcessParams(tool_agfexport, String::FromFormat("glvar %s %s/_GlobalVariables.ash %s/_GlobalVariables.asc --no-empty %s", src_agf.GetCStr(), temp_dir.GetCStr(), temp_dir.GetCStr(), verbose))));
        taskmgr.AddTask(std::make_unique<TaskPipedProcess>("dlgasc", &taskmgr,
            PipedProcessParams(tool_dlgasc, String::FromFormat("%s %s/__DialogScripts.asc %s", src_agf.GetCStr(), temp_dir.GetCStr(), verbose))));

        deploy_temp_files.push_back("acsetup.cfg");
        pre_deploy_tasks.push_back({"game-cfg"});
    }

    // Build game28.dta
    {
        const String tool_agf2dta = Path::ConcatPaths(sys_dir, ToolAgf2Dta);
        taskmgr.AddTask(std::make_unique<TaskPipedProcess>("agf2dta", &taskmgr,
            PipedProcessParams(tool_agf2dta, String::FromFormat("%s %s/game28.dta %s", src_agf.GetCStr(), temp_dir.GetCStr(), verbose))));
        pak_temp_files.push_back("game28.dta");
        pre_pack_tasks.push_back({"agf2dta"});
    }

    // Compile game scripts
    String all_script_headers;
    std::vector<String> scom_modules_list; // compiled scripts that must be listed in ScriptModules.lst
    {
        const String tool_agscc = Path::ConcatPaths(sys_dir, ScriptCompiler);
        String base_headers = String::FromFormat("%s/%s;%s/%s", sys_dir.GetCStr(), ScriptAPIHeader, temp_dir.GetCStr(), ScriptAutoHeader);
        std::vector<String> scom_obj;
        std::vector<String> scom_tasks;

        if (has_globalvar_script)
        {
            base_headers.AppendFmt(";%s/%s", temp_dir.GetCStr(), ScriptGlvarHeader);
            const String task_name = String::FromFormat("agscc:%s", ScriptGlvarScript);
            taskmgr.AddTask(std::unique_ptr<Task>(new TaskPipedProcess(task_name, &taskmgr,
                PipedProcessParams(tool_agscc, String::FromFormat("%s/%s -H %s -o %s/%s %s", temp_dir.GetCStr(), ScriptGlvarScript, base_headers.GetCStr(), temp_dir.GetCStr(), ScriptGlvarScom, verbose)),
                {{"autoash"}, {"glvar"}})));
            scom_obj.push_back(ScriptGlvarScom);
            scom_tasks.push_back(task_name);
        }

        {
            String headers = base_headers;
            for (size_t sm = 0; sm < scm_list.size(); ++sm)
            {
                if (sm < scm_header_list.size())
                    headers.AppendFmt(";%s/%s", src_dir.GetCStr(), scm_header_list[sm].GetCStr());
                const String scm_obj = Path::ReplaceExtension(scm_list[sm], "o");
                const String task_name = String::FromFormat("agscc:%s", scm_list[sm].GetCStr());
                taskmgr.AddTask(std::unique_ptr<Task>(new TaskPipedProcess(task_name, &taskmgr,
                    PipedProcessParams(tool_agscc, String::FromFormat("%s/%s -H %s -o %s/%s %s", src_dir.GetCStr(), scm_list[sm].GetCStr(), headers.GetCStr(), temp_dir.GetCStr(), scm_obj.GetCStr(), verbose)),
                    {{"autoash"}, {"glvar"}})));
                scom_obj.push_back(scm_obj);
                scom_tasks.push_back(task_name);
            }
            all_script_headers = headers;
        }
        // TODO: perhaps write all, and let engine filter global script (and other special scripts) out?
        for (const auto scm : scom_obj)
            if (scm != "GlobalScript.o")
                scom_modules_list.push_back(scm);

        {
            // Dialog script uses all the accumulated script module headers
            const String task_name = String::FromFormat("agscc:%s", ScriptDialogScript);
            taskmgr.AddTask(std::unique_ptr<Task>(new TaskPipedProcess(task_name, &taskmgr,
                PipedProcessParams(tool_agscc, String::FromFormat("%s/%s -H %s -o %s/%s %s", temp_dir.GetCStr(), ScriptDialogScript, all_script_headers.GetCStr(), temp_dir.GetCStr(), ScriptDialogScom, verbose)),
                {{"autoash"}, {"glvar"}, {"dlgasc"}})));
            // NOTE: dialog script is special and is not added to the "script modules" list
            scom_obj.push_back(ScriptDialogScom);
            scom_tasks.push_back(task_name);
        }

        std::copy(scom_obj.begin(), scom_obj.end(), std::back_inserter(pak_temp_files));
        std::copy(scom_tasks.begin(), scom_tasks.end(), std::back_inserter(pre_pack_tasks));
    }

    // Compile room scripts and prepare output room CRM files (without embedded scripts)
    {
        const String tool_crmpak = Path::ConcatPaths(sys_dir, ToolCrmPak);
        const String tool_agscc = Path::ConcatPaths(sys_dir, ScriptCompiler);

        // Copy room files to temp dir, because we need to modify them
        std::vector<std::pair<String, String>> copy_rooms;
        for (const auto &r : room_list_crm)
            copy_rooms.push_back(std::make_pair(Path::ConcatPaths(src_dir, r), Path::ConcatPaths(temp_dir, r)));
        taskmgr.AddTask(std::unique_ptr<Task>(new TaskMoveFiles("copy-rooms", &taskmgr, copy_rooms, true /* copy */, false /* no skip */)));

        // Add tasks for each room
        for (const auto &r : room_list_crm)
        {
            const String room_asc = Path::ReplaceExtension(r, "asc");
            const String room_ash = Path::ReplaceExtension(r, "ash");
            const String room_scom = Path::ReplaceExtension(r, "o");
            const String task_cut_script = String::FromFormat("crmpak:%s:cut-old-scripts", r.GetCStr());
            const String task_ash = String::FromFormat("crmpak:%s:ash", r.GetCStr());
            // Cut old scripts (we may skip this if we decide to import new scripts into room file instead)
            taskmgr.AddTask(std::unique_ptr<Task>(new TaskPipedProcess(task_cut_script, &taskmgr,
                PipedProcessParams(tool_crmpak, String::FromFormat("%s/%s -x script %s", temp_dir.GetCStr(), r.GetCStr(), verbose)),
                {{"copy-rooms"}})));
            // Export room script header
            taskmgr.AddTask(std::unique_ptr<Task>(new TaskPipedProcess(task_ash, &taskmgr,
                PipedProcessParams(tool_crmpak, String::FromFormat("%s/%s -e ash %s/%s.ash %s", temp_dir.GetCStr(), r.GetCStr(), temp_dir.GetCStr(), room_ash.GetCStr(), verbose)),
                {{"copy-rooms"}})));
            // Compile room script
            const String room_headers = String::FromFormat("%s;%s/%s", all_script_headers.GetCStr(), temp_dir.GetCStr(), room_ash.GetCStr());
            const String room_agscc_task = String::FromFormat("agscc:%s", room_asc.GetCStr());
            taskmgr.AddTask(std::unique_ptr<Task>(new TaskPipedProcess(room_agscc_task, &taskmgr,
                PipedProcessParams(tool_agscc, String::FromFormat("%s/%s -H %s -o %s/%s %s", src_dir.GetCStr(), room_asc.GetCStr(), room_headers.GetCStr(), temp_dir.GetCStr(), room_scom.GetCStr(), verbose)),
                {{"autoash"}, {"glvar"}, {task_cut_script}, {task_ash}})));

            pak_temp_files.push_back(r);
            pak_temp_files.push_back(room_scom);
            pre_pack_tasks.push_back(room_agscc_task);
        }
    }

    // Write ScriptModules.lst
    {
        taskmgr.AddTask(std::unique_ptr<Task>(new TaskWriteStringList("write-script-list", &taskmgr,
            Path::ConcatPaths(temp_dir, "ScriptModules.lst"), scom_modules_list)));
        pak_temp_files.push_back("ScriptModules.lst");
        pre_pack_tasks.push_back({"write-script-list"});
    }

    // Rebuild sprite file if necessary / possible;
    // collect either one in source dir, or the one we built in temp dir to the list of packed files
    {
        const String src_spritefile = Path::ConcatPaths(src_dir, "acsprset.spr");
        const String src_spriteindexfile = Path::ConcatPaths(src_dir, "sprindex.dat");
        if (bopts.ReimportSprites || !File::IsFile(src_spritefile))
        {
            // TODO: get sprite packaging options from game settings
            const String tool_spriteimport = Path::ConcatPaths(sys_dir, ToolSpriteImport);
            taskmgr.AddTask(std::unique_ptr<Task>(new TaskPipedProcess("spriteimport", &taskmgr,
                PipedProcessParams(tool_spriteimport, String::FromFormat("-c %s %s/acsprset.spr -n %s/sprindex.dat %s", src_agf.GetCStr(), temp_dir.GetCStr(), temp_dir.GetCStr(), verbose)))));
            pak_temp_files.push_back("acsprset.spr");
            pak_temp_files.push_back("sprindex.dat");
            pre_pack_tasks.push_back({"spriteimport"});
        }
        else
        {
            pak_src_files.push_back("acsprset.spr");
            if (File::IsFile(src_spriteindexfile))
                pak_src_files.push_back("sprindex.dat");
        }
    }

    // Reimport audio clips, if necessary / possible;
    // collect either ones in source dir, or the ones we import onto the temp dir to the list of packed files
    if (aclip_list.size() > 0)
    {
        std::vector<DataUtil::AudioClipData> src_clips;
        std::vector<DataUtil::AudioClipData> temp_clips;
        for (const auto &aclip : aclip_list)
        {
            // TODO: do we need to check file times here? is it this tool's concern? need extra cmd arg?
            if (bopts.ReimportAudio || !File::IsFile(Path::ConcatPaths(audiocache_dir, aclip.CacheFileName)))
                temp_clips.push_back(aclip);
            else
                src_clips.push_back(aclip);
        }

        if (temp_clips.size() > 0)
        {
            const String temp_audio_dir = Path::ConcatPaths(bopts.TempDir, "AudioCache");
            if (!Directory::CreateDirectory(temp_audio_dir))
                return new Error(String::FromFormat("Error: failed to create temporary audio cache directory '%s'", temp_audio_dir.GetCStr()));

            std::vector<std::pair<String, String>> copy_aclips;
            for (const auto &aclip : temp_clips)
            {
                copy_aclips.push_back(std::make_pair(aclip.SourceFileName, Path::ConcatPaths(temp_audio_dir, aclip.CacheFileName)));
                if (aclip.BundlingType == DataUtil::kAudioBundling_InMainData)
                    //pak_temp_files.push_back(String::FromFormat("AudioCache/%s", aclip.CacheFileName.GetCStr()));
                    pak_temp_files.push_back(aclip.CacheFileName);
                else
                    //avox_temp_files.push_back(String::FromFormat("AudioCache/%s", aclip.CacheFileName.GetCStr()));
                    avox_temp_files.push_back(aclip.CacheFileName);
            }
            taskmgr.AddTask(std::unique_ptr<Task>(new TaskMoveFiles("import-audio", &taskmgr, copy_aclips,
                true /* copy */, true /* skip non-existing */, {})));
            pre_pack_tasks.push_back({"import-audio"});
        }

        for (const auto &aclip : src_clips)
        {
            if (aclip.BundlingType == DataUtil::kAudioBundling_InMainData)
                //pak_src_files.push_back(String::FromFormat("AudioCache/%s", aclip.CacheFileName.GetCStr()));
                pak_src_files.push_back(aclip.CacheFileName);
            else
                //avox_src_files.push_back(String::FromFormat("AudioCache/%s", aclip.CacheFileName.GetCStr()));
                avox_src_files.push_back(aclip.CacheFileName);
        }
    }

    // Collect other necessary files from the source directory
    {
        // Add font files
        for (const auto &fnt : font_list)
        {
            const String ttf_file = String::FromFormat("agsfnt%d.ttf", fnt);
            const String wfn_file = String::FromFormat("agsfnt%d.wfn", fnt);
            if (File::IsFile(Path::ConcatPaths(src_dir, ttf_file)))
                pak_src_files.push_back(ttf_file);
            if (File::IsFile(Path::ConcatPaths(src_dir, wfn_file)))
                pak_src_files.push_back(wfn_file);
        }

        // Gather list of valid custom directories
        for (const auto &cd : custom_dirs)
        {
            // Don't allow absolute paths
            if (!Path::IsRelativePath(cd))
                continue;

            // Don't let a custom path equal to the source dir
            if (Path::ComparePaths(src_dir, cd) == 0)
                continue;

            // Don't allow paths to outside of the source dir
            if (!Path::IsSameOrSubDir(src_dir, cd))
                continue;

            // TODO: // don't allow paths that match or inside restricted folders,
            // or folders that were already used to make a list of assets

            pak_custom_dirs.push_back(cd);
        }
    }

    // Pack selected files into game.ags
    {
        const String tool_agspak = Path::ConcatPaths(sys_dir, ToolAgsPak);

        // TODO: write a include file instead, as list of files may become far too large of a command line arg!
        String file_filter;
        for (const auto &f : pak_src_files)
            file_filter.AppendFmt("%s,", f.GetCStr());
        for (const auto &f : pak_temp_files)
            file_filter.AppendFmt("%s,", f.GetCStr());
        for (const auto &cd : pak_custom_dirs)
            file_filter.AppendFmt("%s/*,", cd.GetCStr());
        file_filter.ClipRight(1); // cut last comma

        String game_pack_name = String::FromFormat("%s.ags", game_file_name.GetCStr());
        taskmgr.AddTask(std::unique_ptr<Task>(new TaskPipedProcess("agspak:game.ags", &taskmgr,
            PipedProcessParams(tool_agspak, String::FromFormat("-c %s/%s %s -D %s %s --replace-dup %s",
                temp_dir.GetCStr(), // output pak dir
                game_pack_name.GetCStr(), // game.ags name
                src_dir.GetCStr(), // main input dir
                temp_dir.GetCStr(), // temp output dir (additional input dir)
                file_filter.GetCStr(), // file match filter
                verbose
            )), pre_pack_tasks)));

        deploy_temp_files.push_back(game_pack_name);
        pre_deploy_tasks.push_back({"agspak:game.ags"});
    }

    // Pack selected files into audio.vox
    if (avox_src_files.size() > 0 || avox_temp_files.size() > 0)
    {
        const String tool_agspak = Path::ConcatPaths(sys_dir, ToolAgsPak);

        // TODO: write a include file instead, as list of files may become far too large of a command line arg!
        String file_filter;
        for (const auto &f : avox_src_files)
            file_filter.AppendFmt("%s,", f.GetCStr());
        for (const auto &f : avox_temp_files)
            file_filter.AppendFmt("%s,", f.GetCStr());
        file_filter.ClipRight(1); // cut last comma

        taskmgr.AddTask(std::unique_ptr<Task>(new TaskPipedProcess("agspak:audio.vox", &taskmgr,
            PipedProcessParams(tool_agspak, String::FromFormat("-c %s/audio.vox %s/AudioCache -D %s/AudioCache %s --replace-dup %s",
                temp_dir.GetCStr(), // output pak dir
                src_dir.GetCStr(), // main input dir
                temp_dir.GetCStr(), // temp output dir (additional input dir)
                file_filter.GetCStr(), // file match filter
                verbose
            )), pre_pack_tasks)));

        deploy_temp_files.push_back("audio.vox");
        pre_deploy_tasks.push_back({"agspak:audio.vox"});
    }

    // Pack selected files into speech.vox
    // TODO: include lipsync files
    // TODO: support multiple speech voxes
    // FIXME: use speech_file_filter in HasAnyFiles, but must make it support multi-pattern
    const String speech_file_filter = "*.mp3,*.ogg,*.wav";
    if (Directory::HasAnyFiles(speech_dir))
    {
        const String tool_agspak = Path::ConcatPaths(sys_dir, ToolAgsPak);

        taskmgr.AddTask(std::unique_ptr<Task>(new TaskPipedProcess("agspak:speech.vox", &taskmgr,
            PipedProcessParams(tool_agspak, String::FromFormat("-c %s/speech.vox %s/Speech %s --replace-dup %s",
                temp_dir.GetCStr(), // output pak dir
                src_dir.GetCStr(), // main input dir
                speech_file_filter.GetCStr(), // file match filter
                verbose
            )), pre_pack_tasks)));

        deploy_temp_files.push_back("speech.vox");
        pre_deploy_tasks.push_back({"agspak:speech.vox"});
    }

    // Move final files to the destination dir
    {
        std::vector<std::pair<String, String>> deploy_data;
        for (const auto &f : deploy_temp_files)
            deploy_data.push_back(std::make_pair(Path::ConcatPaths(temp_dir, f), Path::ConcatPaths(out_dir, f)));
        taskmgr.AddTask(std::unique_ptr<Task>(new TaskMoveFiles("deploy-data", &taskmgr, deploy_data,
            false /* move */, false /* no skip */, pre_deploy_tasks)));
    }

    return taskmgr.RunAll();
}


const char *HELP_STRING = ""
//--------------------------------------------------------------------------------|
"agsbuild v0.1.0 - AGS game project build tool\n"
"Copyright (c) 2026 AGS Team and contributors\n"
"Usage: agsbuild [<OPTIONS>] <input-game.agf> <out-dir> <temp-dir>\n"
"\n"
"Options:\n"
"  --import-audio         generate a new audio cache, importing audio files from\n"
"                         the source files, according to game.agf specs.\n"
"  --import-sprites       create a new sprite pack, importing sprites from the\n"
"                         source image files, according to game.agf specs.\n"
"                         Requires a presence of spriteimport tool.\n"
"  -t, --threads <N>      limit task threads to this number (default: 8);\n"
"                         note that tasks may spawn new processes, executing other\n"
"                         tools.\n"
"  -v, --verbose          print operation details (also affects spawned processes)\n"
;

int main(int argc, char *argv[])
{
    CmdLineOpts::ParseResult cmdargs = CmdLineOpts::Parse(argc, argv, {"-t", "--threads"});
    if (cmdargs.HelpRequested)
    {
        printf("%s\n", HELP_STRING);
        return 0; // display help and bail out
    }

    BuildOptions bopts;
    bopts.SrcAgf = argv[1];
    bopts.OutDir = argv[2];
    bopts.SrcDir = Path::GetParent(bopts.SrcAgf);
    bopts.SysDir = Directory::GetCurrentDirectory();
    bopts.TempDir = argc >= 4 ? argv[3] : Path::ConcatPaths(bopts.OutDir, "_temp");
    const bool temp_dir_owned = argc < 4;
    bopts.ReimportAudio = cmdargs.Opt.count("--import-audio") > 0;
    bopts.ReimportSprites = cmdargs.Opt.count("--import-sprites") > 0;
    bopts.Verbose = cmdargs.Opt.count("-v") > 0 || cmdargs.Opt.count("--verbose") > 0;
    for (const auto &opt : cmdargs.OptWithValue)
    {
        if (opt.first == "-t" || opt.first == "--threads")
            bopts.TaskThreads = StrUtil::StringToInt(opt.second);
    }

    //-------------------------------------------------------------------------
    // Preliminary checks
    //-------------------------------------------------------------------------
    if (!File::IsFile(bopts.SrcAgf))
    {
        printf("Error: input project file '%s' not found or not a valid file", bopts.SrcAgf.GetCStr());
        return -1;
    }
    if (!File::IsDirectory(bopts.SrcDir))
    {
        printf("Error: input project directory '%s' not found or not a valid directory", bopts.SrcDir.GetCStr());
        return -1;
    }
    if (!File::IsDirectory(bopts.OutDir))
    {
        printf("Error: output directory '%s' not found or not a valid directory", bopts.OutDir.GetCStr());
        return -1;
    }

    //-------------------------------------------------------------------------
    // Prepare
    //-------------------------------------------------------------------------
    if (temp_dir_owned && !Directory::CreateDirectory(bopts.TempDir))
    {
        printf("Error: failed to create temporary output directory '%s'", bopts.TempDir.GetCStr());
        return -1;
    }

    HError err = BuildWithTaskManager(bopts);

    //-------------------------------------------------------------------------
    // Cleanup
    //-------------------------------------------------------------------------
    if (temp_dir_owned)
    {
        Directory::DeleteDirectory(bopts.TempDir);
    }

    if (!err)
        printf("%s\n", err->FullMessage().GetCStr());
    return err ? 0 : -1;
}
