#!/bin/sh
SCRIPTPATH="$(dirname "$(readlink -f $0)")"

if test "x$@" = "x-h" -o "x$@" = "x--help"
  then
    echo "Usage:" "$(basename "$(readlink -f $0)")" "[<ags options>]"
    echo ""
fi

if test $(uname -m) = x86_64
  then
    export LD_LIBRARY_PATH="$SCRIPTPATH/lib64":$LD_LIBRARY_PATH
    ALLEGRO_MODULES="$SCRIPTPATH/data/lib64" "$SCRIPTPATH/data/ags64" "$@" "$SCRIPTPATH/data/"
  else
    export LD_LIBRARY_PATH="$SCRIPTPATH/lib32":$LD_LIBRARY_PATH
    ALLEGRO_MODULES="$SCRIPTPATH/data/lib32" "$SCRIPTPATH/data/ags32" "$@" "$SCRIPTPATH/data/"
fi
