//=============================================================================
//
// Adventure Game Studio (AGS)
//
// Copyright (C) 1999-2011 Chris Jones and 2011-2025 various contributors
// The full list of copyright holders can be found in the Copyright.txt
// file, which is part of this source code distribution.
//
// The AGS source code is provided under the Artistic License 2.0.
// A copy of this license can be found in the file License.txt and at
// https://opensource.org/license/artistic-2-0/
//
//=============================================================================
#include <vector>
#include "makefile_writer.h"
#include "data/agfreader.h"
#include "generator_common.h"

using namespace AGS;
using namespace AGS::Common;
using namespace WriterUtils;

// Note on Makefile
// The $@ and $< are called automatic variables.
// - The variable $@ represents the name of the target;
// - The variable $< represents the first prerequisite required to create the output file.

namespace MakefileGenerator
{

void GenerateMakefile(const GeneratorOptions &opt, std::unique_ptr<Stream> &&out)
{
    MakefileWriter writer(std::move(out));

    const std::vector<String> crm_list = opt.RoomFileList;
    const std::vector<String> headers_list = opt.HeaderFileList;
    const std::vector<String> scripts_list = opt.ScriptFileList;
    const std::vector<String> trs_files = opt.TrsFileList;

    std::vector<String> project_headers;
    project_headers.reserve(headers_list.size());
    for (const auto &header : headers_list)
        project_headers.push_back(String::FromFormat("$(GAME_PROJECT_DIR)/%s", header.GetCStr()));

    writer.Comment("Makefile for AGS GAME");
    // Variables
    writer.Variable("AGSCC", opt.ToolAgscc);
    writer.Variable("AGFEXPORT", opt.ToolAgfexport);
    writer.Variable("AGF2DLASC", opt.ToolAgf2dlgasc);
    writer.Variable("TRAC", opt.ToolTrac);
    writer.Variable("AGSPAK", opt.ToolAgspak);
    writer.Variable("CRMPAK", opt.ToolCrmpak);
    writer.Variable("AGF2DTA", opt.ToolAgf2dta);
    writer.Variable("GAME_PROJECT_DIR", opt.GameProjectDir);
    writer.Variable("GAME_PROJECT_FILE", opt.GameProjectFile);
    writer.Variable("OUTPUT_DIR", opt.OutputDir);
    writer.Variable("TEMP_DIR", opt.TempDir);
    writer.Variable("AGSDEFNS_FILE", opt.AgsDefnsFile);
    writer.Variable("GAME_FILENAME", opt.GameFileName);

    // Auto headers
    writer.Rule("$(TEMP_DIR)/_AutoGenerated.ash", {"$(GAME_PROJECT_FILE)"}, "$(AGFEXPORT) autoash $< $@");
    writer.Rule("$(TEMP_DIR)/_GlobalVariables.ash", {"$(GAME_PROJECT_FILE)"},"$(AGFEXPORT) glvar $< $(TEMP_DIR)/_GlobalVariables.ash $(TEMP_DIR)/_GlobalVariables.asc");
    writer.Rule("$(TEMP_DIR)/__DialogScripts.asc", {"$(GAME_PROJECT_FILE)"}, "$(AGF2DLASC) $< $@");

    // Compile script modules
    std::vector<String> headers_base {"$(AGSDEFNS_FILE)","$(TEMP_DIR)/_AutoGenerated.ash","$(TEMP_DIR)/_GlobalVariables.ash"};

    for (int i = 0; i < scripts_list.size(); i++)
    {
        const auto &script = scripts_list[i];

        String scriptname = script.Left(script.GetLength() - 4); // Strip extension
        String asc = String::FromFormat("$(GAME_PROJECT_DIR)/%s", script.GetCStr());
        String obj = String::FromFormat("$(TEMP_DIR)/%s.o", scriptname.GetCStr());

        std::vector<String> this_script_headers(headers_base);
        this_script_headers.insert(this_script_headers.end(), project_headers.begin(), project_headers.begin() + i);
        // FIX-ME: revise this, I think I forgot the header of the script that is actually passed to agscc!!
        String headers = Join(":", this_script_headers);

        std::vector<String> dependencies(this_script_headers);
        dependencies.push_back(asc);
        String cmd = String::FromFormat("$(AGSCC) %s -o %s -H %s", asc.GetCStr(), obj.GetCStr(), headers.GetCStr());

        writer.Rule(obj, dependencies, cmd);
    }

    // Compile dialog script
    if (opt.HasDialogScripts)
    {
        String asc = "$(TEMP_DIR)/__DialogScripts.asc";
        String obj = "$(TEMP_DIR)/DialogScripts.o";
        std::vector<String> script_headers(headers_base);
        script_headers.insert(script_headers.end(), project_headers.begin(), project_headers.end());
        String headers = Join(":", script_headers);

        std::vector<String> dependencies(script_headers);
        dependencies.push_back(asc);

        String cmd = String::FromFormat("$(AGSCC) %s -o %s -H %s", asc.GetCStr(), obj.GetCStr(), headers.GetCStr());

        writer.Rule(obj, dependencies, cmd);
    }

    // Handle rooms
    for (const auto &crm : crm_list)
    {
        String room = crm.Left(crm.GetLength() - 4); // Strip ".crm" extension
        String room_header = String::FromFormat("$(TEMP_DIR)/%s.ash", room.GetCStr());
        String room_asc = String::FromFormat("$(GAME_PROJECT_DIR)/%s.asc", room.GetCStr());
        String room_obj = String::FromFormat("$(TEMP_DIR)/%s.o", room.GetCStr());
        String room_crm_source = String::FromFormat("$(GAME_PROJECT_DIR)/%s", crm.GetCStr());
        String room_crm_built = String::FromFormat("$(TEMP_DIR)/%s", crm.GetCStr());

        writer.Rule(room_header, { room_crm_source }, "$(CRMPAK) -e $< ash $@");

        // Compile the room script.
        // FIX-ME: revise this because it is not efficient? Perhaps do some outside the loop??
        std::vector<String> room_headers(headers_base);
        room_headers.insert(room_headers.end(), project_headers.begin(), project_headers.end());
        room_headers.push_back(room_header);
        String headers = Join(":", room_headers);

        std::vector<String> room_deps(room_headers);
        room_deps.push_back(room_asc);
        String room_cmd = String::FromFormat("$(AGSCC) %s -o %s -H %s", room_asc.GetCStr(), room_obj.GetCStr(), headers.GetCStr());
        writer.Rule(room_obj, room_deps, room_cmd);

        // Patch the compiled script into a copy of the room, to be picked by agspak
        // NOTE: need to revise this, perhaps we can just patch any script from the room and include it separately
        String import_cmd = String::FromFormat("$(CRMPAK) -i %s script %s -w %s", room_crm_source.GetCStr(), room_obj.GetCStr(), room_crm_built.GetCStr());
        writer.Rule(room_crm_built, { room_crm_source, room_obj }, import_cmd);
    }

    // Generate TRA files from TRS files using trac.exe
    for (const auto &trs : trs_files)
    {
        String tra = trs.Left(trs.GetLength() - 4); // Strip ".trs" extension
        writer.Rule(String::FromFormat("$(TEMP_DIR)/%s.tra", tra.GetCStr()),
                    {String::FromFormat("$(GAME_PROJECT_DIR)/%s", trs.GetCStr())},
                    "$(TRAC) $< $@");
    }

    // build game28.dta
    writer.Rule("$(TEMP_DIR)/game28.dta", {"$(GAME_PROJECT_FILE)"}, "$(AGF2DTA) $< $@");

    // Package the game files using agspak.
    // FIX-ME: review all this, we are missing sound and this looks complicated
    {
        std::vector<String> pak_files;
        std::vector<String> pak_deps;

        pak_files.push_back("game28.dta");
        pak_deps.push_back("$(TEMP_DIR)/game28.dta");

        for (const auto& script : scripts_list)
        {
            String scriptname = script.Left(script.GetLength() - 4); // Strip extension
            pak_files.push_back(String::FromFormat("%s.o", scriptname.GetCStr()));
            pak_deps.push_back(String::FromFormat("$(TEMP_DIR)/%s.o", scriptname.GetCStr()));
        }

        if (opt.HasDialogScripts)
        {
            pak_files.push_back("DialogScripts.o");
            pak_deps.push_back("$(TEMP_DIR)/DialogScripts.o");
        }        
        
        pak_files.push_back("ScriptModules.lst");
        pak_deps.push_back("$(TEMP_DIR)/ScriptModules.lst");

        for (const auto& trs : trs_files)
        {
            String tra = trs.Left(trs.GetLength() - 4); // Strip ".trs" extension
            pak_files.push_back(String::FromFormat("%s.tra", tra.GetCStr()));
            pak_deps.push_back(String::FromFormat("$(TEMP_DIR)/%s.tra", tra.GetCStr()));
        }

        // NOTE: rooms are packaged from the patched copy
        for (const auto& crm : crm_list)
        {
            pak_files.push_back(crm);
            pak_deps.push_back(String::FromFormat("$(TEMP_DIR)/%s", crm.GetCStr()));
        }

        pak_files.push_back("acsprset.spr");
        pak_files.push_back("sprindex.dat");
        pak_deps.push_back("$(GAME_PROJECT_DIR)/acsprset.spr");
        pak_deps.push_back("$(GAME_PROJECT_DIR)/sprindex.dat");

        String file_filter = Join(",", pak_files);
        String cmd = String::FromFormat("$(AGSPAK) -c $@ $(GAME_PROJECT_DIR) -D $(TEMP_DIR) %s --replace-dup", file_filter.GetCStr());

        writer.Rule("$(OUTPUT_DIR)/$(GAME_FILENAME)", pak_deps, cmd);
    }

    // Package the audio and speech files
    // FIX-ME: these should also be conditioned to settings from Game.agf
    // writer.Rule("audio.vox", {"AudioCache/*"}, "$(AGSPAK) $^ $@");
    // writer.Rule("speech.vox", {"Speech/*"}, "$(AGSPAK) $^ $@");

}

} // namespace MakefileGenerator
