using System;
using System.IO;
using System.Text;
using System.Xml;
using AGS.Types;

namespace AGS.CommandLine.Services
{
    /// <summary>
    /// Saves a Game object back to Game.agf using the same format as the AGS Editor.
    /// Uses atomic write (temp file → rename) to avoid corruption.
    /// </summary>
    public static class GameSaver
    {
        private const string ROOT_NODE = "AGSEditorDocument";

        public static void Save(Game game, string projectPath)
        {
            if (game == null) throw new ArgumentNullException("game");
            if (string.IsNullOrEmpty(projectPath)) throw new ArgumentException("projectPath is required");

            string gameFile   = Path.Combine(projectPath, "Game.agf");
            string tempFile   = Path.Combine(projectPath, "Game.agf.tmp");
            string backupFile = Path.Combine(projectPath, "Game.agf.bak");

            // Preserve the version attributes exactly as they were in the original file.
            // Using a hardcoded VersionIndex would downgrade the project format and
            // cause the AGS Editor to reject properties introduced in newer versions.
            string xmlVersion   = game.SavedXmlVersion      ?? "3.0.3.2";
            string versionIndex = game.SavedXmlVersionIndex.HasValue
                ? game.SavedXmlVersionIndex.Value.ToString()
                : "43";
            string editorVersion = game.SavedXmlEditorVersion ?? "3.6.3.11";

            // Mark all scripts unmodified before ToXml so SaveToDisk skips them.
            foreach (ScriptAndHeader sh in game.ScriptsAndHeaders)
            {
                if (sh.Script != null) sh.Script.Modified = false;
                if (sh.Header != null) sh.Header.Modified = false;
            }

            string previousDir = Directory.GetCurrentDirectory();
            try
            {
                Directory.SetCurrentDirectory(projectPath);

                Encoding enc = game.TextEncoding ?? Encoding.UTF8;
                StringWriter sw = new StringWriter();
                XmlTextWriter writer = new XmlTextWriter(sw);
                writer.Formatting = Formatting.Indented;
                writer.WriteProcessingInstruction("xml",
                    string.Format("version=\"1.0\" encoding=\"{0}\"", enc.WebName));
                writer.WriteComment(
                    "DO NOT EDIT THIS FILE. It is automatically generated by the AGS Editor, " +
                    "changing it manually could break your game");
                writer.WriteStartElement(ROOT_NODE);
                writer.WriteAttributeString("Version", xmlVersion);
                writer.WriteAttributeString("VersionIndex", versionIndex);
                writer.WriteAttributeString("EditorVersion", editorVersion);

                game.ToXml(writer);

                writer.WriteEndElement();
                writer.Flush();
                string xml = sw.ToString();
                writer.Close();

                using (StreamWriter fileOut = new StreamWriter(tempFile, false, enc))
                {
                    fileOut.Write(xml);
                    fileOut.Flush();
                }

                if (File.Exists(gameFile))
                {
                    if (File.Exists(backupFile)) File.Delete(backupFile);
                    File.Move(gameFile, backupFile);
                }
                File.Move(tempFile, gameFile);
            }
            finally
            {
                Directory.SetCurrentDirectory(previousDir);
            }
        }
    }
}
