//=============================================================================
//
// Adventure Game Studio (AGS)
//
// Copyright (C) 1999-2011 Chris Jones and 2011-20xx others
// The full list of copyright holders can be found in the Copyright.txt
// file, which is part of this source code distribution.
//
// The AGS source code is provided under the Artistic License 2.0.
// A copy of this license can be found in the file License.txt and at
// http://www.opensource.org/licenses/artistic-license-2.0.php
//
//=============================================================================
//
// Exporting global script functions
//
//=============================================================================

// the ^n after the function name is the number of params
// this is to allow an extra parameter to be added in a later
// version without screwing up the stack in previous versions
// (just export both the ^n and the ^m as seperate funcs)

#include "util/wgt2allg.h"
#include "ac/gamestate.h"
#include "script/symbol_registry.h"

void register_global_script_functions()
{
	ccAddExternalStaticFunction("AbortGame",(void *)_sc_AbortGame);
	ccAddExternalStaticFunction("AddInventory",(void *)add_inventory);
	ccAddExternalStaticFunction("AddInventoryToCharacter",(void *)AddInventoryToCharacter);
	ccAddExternalStaticFunction("AnimateButton",(void *)AnimateButton);
	ccAddExternalStaticFunction("AnimateCharacter",(void *)scAnimateCharacter);
	ccAddExternalStaticFunction("AnimateCharacterEx",(void *)AnimateCharacterEx);
	ccAddExternalStaticFunction("AnimateObject",(void *)AnimateObject);
	ccAddExternalStaticFunction("AnimateObjectEx",(void *)AnimateObjectEx);
	ccAddExternalStaticFunction("AreCharactersColliding",(void *)AreCharactersColliding);
	ccAddExternalStaticFunction("AreCharObjColliding",(void *)AreCharObjColliding);
	ccAddExternalStaticFunction("AreObjectsColliding",(void *)AreObjectsColliding);
	ccAddExternalStaticFunction("AreThingsOverlapping",(void *)AreThingsOverlapping);
	ccAddExternalStaticFunction("CallRoomScript",(void *)CallRoomScript);
	ccAddExternalStaticFunction("CDAudio",(void *)cd_manager);
	ccAddExternalStaticFunction("CentreGUI",(void *)CentreGUI);
	ccAddExternalStaticFunction("ChangeCharacterView",(void *)ChangeCharacterView);
	ccAddExternalStaticFunction("ChangeCursorGraphic",(void *)ChangeCursorGraphic);
	ccAddExternalStaticFunction("ChangeCursorHotspot",(void *)ChangeCursorHotspot);
	ccAddExternalStaticFunction("ClaimEvent",(void *)ClaimEvent);
	ccAddExternalStaticFunction("CreateGraphicOverlay",(void *)CreateGraphicOverlay);
	ccAddExternalStaticFunction("CreateTextOverlay",(void *)CreateTextOverlay);
	ccAddExternalStaticFunction("CyclePalette",(void *)CyclePalette);
	ccAddExternalStaticFunction("Debug",(void *)script_debug);
	ccAddExternalStaticFunction("DeleteSaveSlot",(void *)DeleteSaveSlot);
	ccAddExternalStaticFunction("DeleteSprite",(void *)free_dynamic_sprite);
	ccAddExternalStaticFunction("DisableCursorMode",(void *)disable_cursor_mode);
	ccAddExternalStaticFunction("DisableGroundLevelAreas",(void *)DisableGroundLevelAreas);
	ccAddExternalStaticFunction("DisableHotspot",(void *)DisableHotspot);
	ccAddExternalStaticFunction("DisableInterface",(void *)DisableInterface);
	ccAddExternalStaticFunction("DisableRegion",(void *)DisableRegion);
	ccAddExternalStaticFunction("Display",(void *)Display);
	ccAddExternalStaticFunction("DisplayAt",(void *)DisplayAt);
	ccAddExternalStaticFunction("DisplayAtY",(void *)DisplayAtY);
	ccAddExternalStaticFunction("DisplayMessage",(void *)DisplayMessage);
	ccAddExternalStaticFunction("DisplayMessageAtY",(void *)DisplayMessageAtY);
	ccAddExternalStaticFunction("DisplayMessageBar",(void *)DisplayMessageBar);
	ccAddExternalStaticFunction("DisplaySpeech",(void *)__sc_displayspeech);
	ccAddExternalStaticFunction("DisplaySpeechAt", (void *)DisplaySpeechAt);
	ccAddExternalStaticFunction("DisplaySpeechBackground",(void *)DisplaySpeechBackground);
	ccAddExternalStaticFunction("DisplayThought",(void *)DisplayThought);
	ccAddExternalStaticFunction("DisplayTopBar",(void *)DisplayTopBar);
	ccAddExternalStaticFunction("EnableCursorMode",(void *)enable_cursor_mode);
	ccAddExternalStaticFunction("EnableGroundLevelAreas",(void *)EnableGroundLevelAreas);
	ccAddExternalStaticFunction("EnableHotspot",(void *)EnableHotspot);
	ccAddExternalStaticFunction("EnableInterface",(void *)EnableInterface);
	ccAddExternalStaticFunction("EnableRegion",(void *)EnableRegion);
	ccAddExternalStaticFunction("EndCutscene", (void *)EndCutscene);
	ccAddExternalStaticFunction("FaceCharacter",(void *)FaceCharacter);
	ccAddExternalStaticFunction("FaceLocation",(void *)FaceLocation);
	ccAddExternalStaticFunction("FadeIn",(void *)FadeIn);
	ccAddExternalStaticFunction("FadeOut",(void *)my_fade_out);
	ccAddExternalStaticFunction("FileClose",(void *)FileClose);
	ccAddExternalStaticFunction("FileIsEOF",(void *)FileIsEOF);
	ccAddExternalStaticFunction("FileIsError",(void *)FileIsError);
	ccAddExternalStaticFunction("FileOpen",(void *)FileOpen);
	ccAddExternalStaticFunction("FileRead",(void *)FileRead);
	ccAddExternalStaticFunction("FileReadInt",(void *)FileReadInt);
	ccAddExternalStaticFunction("FileReadRawChar",(void *)FileReadRawChar);
	ccAddExternalStaticFunction("FileReadRawInt",(void *)FileReadRawInt);
	ccAddExternalStaticFunction("FileWrite",(void *)FileWrite);
	ccAddExternalStaticFunction("FileWriteInt",(void *)FileWriteInt);
	ccAddExternalStaticFunction("FileWriteRawChar",(void *)FileWriteRawChar);
	ccAddExternalStaticFunction("FileWriteRawLine", (void *)FileWriteRawLine);
	ccAddExternalStaticFunction("FindGUIID",(void *)FindGUIID);
	ccAddExternalStaticFunction("FlipScreen",(void *)FlipScreen);
	ccAddExternalStaticFunction("FloatToInt",(void *)FloatToInt);
	ccAddExternalStaticFunction("FollowCharacter",(void *)FollowCharacter);
	ccAddExternalStaticFunction("FollowCharacterEx",(void *)FollowCharacterEx);
	ccAddExternalStaticFunction("GetBackgroundFrame",(void *)GetBackgroundFrame);
	ccAddExternalStaticFunction("GetButtonPic",(void *)GetButtonPic);
	ccAddExternalStaticFunction("GetCharacterAt",(void *)GetCharacterAt);
	ccAddExternalStaticFunction("GetCharacterProperty",(void *)GetCharacterProperty);
	ccAddExternalStaticFunction("GetCharacterPropertyText",(void *)GetCharacterPropertyText);
	ccAddExternalStaticFunction("GetCurrentMusic",(void *)GetCurrentMusic);
	ccAddExternalStaticFunction("GetCursorMode",(void *)GetCursorMode);
	ccAddExternalStaticFunction("GetDialogOption",(void *)GetDialogOption);
	ccAddExternalStaticFunction("GetGameOption",(void *)GetGameOption);
	ccAddExternalStaticFunction("GetGameParameter",(void *)GetGameParameter);
	ccAddExternalStaticFunction("GetGameSpeed",(void *)GetGameSpeed);
	ccAddExternalStaticFunction("GetGlobalInt",(void *)GetGlobalInt);
	ccAddExternalStaticFunction("GetGlobalString",(void *)GetGlobalString);
	ccAddExternalStaticFunction("GetGraphicalVariable",(void *)GetGraphicalVariable);
	ccAddExternalStaticFunction("GetGUIAt", (void *)GetGUIAt);
	ccAddExternalStaticFunction("GetGUIObjectAt", (void *)GetGUIObjectAt);
	ccAddExternalStaticFunction("GetHotspotAt",(void *)GetHotspotAt);
	ccAddExternalStaticFunction("GetHotspotName",(void *)GetHotspotName);
	ccAddExternalStaticFunction("GetHotspotPointX",(void *)GetHotspotPointX);
	ccAddExternalStaticFunction("GetHotspotPointY",(void *)GetHotspotPointY);
	ccAddExternalStaticFunction("GetHotspotProperty",(void *)GetHotspotProperty);
	ccAddExternalStaticFunction("GetHotspotPropertyText",(void *)GetHotspotPropertyText);
	ccAddExternalStaticFunction("GetInvAt",(void *)GetInvAt);
	ccAddExternalStaticFunction("GetInvGraphic",(void *)GetInvGraphic);
	ccAddExternalStaticFunction("GetInvName",(void *)GetInvName);
	ccAddExternalStaticFunction("GetInvProperty",(void *)GetInvProperty);
	ccAddExternalStaticFunction("GetInvPropertyText",(void *)GetInvPropertyText);
	//ccAddExternalStaticFunction("GetLanguageString",(void *)GetLanguageString);
	ccAddExternalStaticFunction("GetLocationName",(void *)GetLocationName);
	ccAddExternalStaticFunction("GetLocationType",(void *)GetLocationType);
	ccAddExternalStaticFunction("GetMessageText", (void *)GetMessageText);
	ccAddExternalStaticFunction("GetMIDIPosition", (void *)GetMIDIPosition);
	ccAddExternalStaticFunction("GetMP3PosMillis", (void *)GetMP3PosMillis);
	ccAddExternalStaticFunction("GetObjectAt",(void *)GetObjectAt);
	ccAddExternalStaticFunction("GetObjectBaseline",(void *)GetObjectBaseline);
	ccAddExternalStaticFunction("GetObjectGraphic",(void *)GetObjectGraphic);
	ccAddExternalStaticFunction("GetObjectName",(void *)GetObjectName);
	ccAddExternalStaticFunction("GetObjectProperty",(void *)GetObjectProperty);
	ccAddExternalStaticFunction("GetObjectPropertyText",(void *)GetObjectPropertyText);
	ccAddExternalStaticFunction("GetObjectX",(void *)GetObjectX);
	ccAddExternalStaticFunction("GetObjectY",(void *)GetObjectY);
	//  ccAddExternalStaticFunction("GetPalette",(void *)scGetPal);
	ccAddExternalStaticFunction("GetPlayerCharacter",(void *)GetPlayerCharacter);
	ccAddExternalStaticFunction("GetRawTime",(void *)GetRawTime);
	ccAddExternalStaticFunction("GetRegionAt",(void *)GetRegionAt);
	ccAddExternalStaticFunction("GetRoomProperty",(void *)GetRoomProperty);
	ccAddExternalStaticFunction("GetRoomPropertyText",(void *)GetRoomPropertyText);
	ccAddExternalStaticFunction("GetSaveSlotDescription",(void *)GetSaveSlotDescription);
	ccAddExternalStaticFunction("GetScalingAt",(void *)GetScalingAt);
	ccAddExternalStaticFunction("GetSliderValue",(void *)GetSliderValue);
	ccAddExternalStaticFunction("GetTextBoxText",(void *)GetTextBoxText);
	ccAddExternalStaticFunction("GetTextHeight",(void *)GetTextHeight);
	ccAddExternalStaticFunction("GetTextWidth",(void *)GetTextWidth);
	ccAddExternalStaticFunction("GetTime",(void *)sc_GetTime);
	ccAddExternalStaticFunction("GetTranslation", (void *)get_translation);
	ccAddExternalStaticFunction("GetTranslationName", (void *)GetTranslationName);
	ccAddExternalStaticFunction("GetViewportX",(void *)GetViewportX);
	ccAddExternalStaticFunction("GetViewportY",(void *)GetViewportY);
	ccAddExternalStaticFunction("GetWalkableAreaAt",(void *)GetWalkableAreaAt);
	ccAddExternalStaticFunction("GiveScore",(void *)GiveScore);
	ccAddExternalStaticFunction("HasPlayerBeenInRoom",(void *)HasPlayerBeenInRoom);
	ccAddExternalStaticFunction("HideMouseCursor",(void *)HideMouseCursor);
	ccAddExternalStaticFunction("InputBox",(void *)sc_inputbox);
	ccAddExternalStaticFunction("InterfaceOff",(void *)InterfaceOff);
	ccAddExternalStaticFunction("InterfaceOn",(void *)InterfaceOn);
	ccAddExternalStaticFunction("IntToFloat",(void *)IntToFloat);
	ccAddExternalStaticFunction("InventoryScreen",(void *)sc_invscreen);
	ccAddExternalStaticFunction("IsButtonDown",(void *)IsButtonDown);
	ccAddExternalStaticFunction("IsChannelPlaying",(void *)IsChannelPlaying);
	ccAddExternalStaticFunction("IsGamePaused",(void *)IsGamePaused);
	ccAddExternalStaticFunction("IsGUIOn", (void *)IsGUIOn);
	ccAddExternalStaticFunction("IsInteractionAvailable", (void *)IsInteractionAvailable);
	ccAddExternalStaticFunction("IsInventoryInteractionAvailable", (void *)IsInventoryInteractionAvailable);
	ccAddExternalStaticFunction("IsInterfaceEnabled", (void *)IsInterfaceEnabled);
	ccAddExternalStaticFunction("IsKeyPressed",(void *)IsKeyPressed);
	ccAddExternalStaticFunction("IsMusicPlaying",(void *)IsMusicPlaying);
	ccAddExternalStaticFunction("IsMusicVoxAvailable",(void *)IsMusicVoxAvailable);
	ccAddExternalStaticFunction("IsObjectAnimating",(void *)IsObjectAnimating);
	ccAddExternalStaticFunction("IsObjectMoving",(void *)IsObjectMoving);
	ccAddExternalStaticFunction("IsObjectOn",(void *)IsObjectOn);
	ccAddExternalStaticFunction("IsOverlayValid",(void *)IsOverlayValid);
	ccAddExternalStaticFunction("IsSoundPlaying",(void *)IsSoundPlaying);
	ccAddExternalStaticFunction("IsTimerExpired",(void *)IsTimerExpired);
	ccAddExternalStaticFunction("IsTranslationAvailable", (void *)IsTranslationAvailable);
	ccAddExternalStaticFunction("IsVoxAvailable",(void *)IsVoxAvailable);
	ccAddExternalStaticFunction("ListBoxAdd", (void *)ListBoxAdd);
	ccAddExternalStaticFunction("ListBoxClear", (void *)ListBoxClear);
	ccAddExternalStaticFunction("ListBoxDirList", (void *)ListBoxDirList);
	ccAddExternalStaticFunction("ListBoxGetItemText", (void *)ListBoxGetItemText);
	ccAddExternalStaticFunction("ListBoxGetNumItems", (void *)ListBoxGetNumItems);
	ccAddExternalStaticFunction("ListBoxGetSelected", (void *)ListBoxGetSelected);
	ccAddExternalStaticFunction("ListBoxRemove", (void *)ListBoxRemove);
	ccAddExternalStaticFunction("ListBoxSaveGameList", (void *)ListBoxSaveGameList);
	ccAddExternalStaticFunction("ListBoxSetSelected", (void *)ListBoxSetSelected);
	ccAddExternalStaticFunction("ListBoxSetTopItem", (void *)ListBoxSetTopItem);
	ccAddExternalStaticFunction("LoadImageFile",(void *)LoadImageFile);
	ccAddExternalStaticFunction("LoadSaveSlotScreenshot",(void *)LoadSaveSlotScreenshot);
	ccAddExternalStaticFunction("LoseInventory",(void *)lose_inventory);
	ccAddExternalStaticFunction("LoseInventoryFromCharacter",(void *)LoseInventoryFromCharacter);
	ccAddExternalStaticFunction("MergeObject",(void *)MergeObject);
	ccAddExternalStaticFunction("MoveCharacter",(void *)MoveCharacter);
	ccAddExternalStaticFunction("MoveCharacterBlocking",(void *)MoveCharacterBlocking);
	ccAddExternalStaticFunction("MoveCharacterDirect",(void *)MoveCharacterDirect);
	ccAddExternalStaticFunction("MoveCharacterPath",(void *)MoveCharacterPath);
	ccAddExternalStaticFunction("MoveCharacterStraight",(void *)MoveCharacterStraight);
	ccAddExternalStaticFunction("MoveCharacterToHotspot",(void *)MoveCharacterToHotspot);
	ccAddExternalStaticFunction("MoveCharacterToObject",(void *)MoveCharacterToObject);
	ccAddExternalStaticFunction("MoveObject",(void *)MoveObject);
	ccAddExternalStaticFunction("MoveObjectDirect",(void *)MoveObjectDirect);
	ccAddExternalStaticFunction("MoveOverlay",(void *)MoveOverlay);
	ccAddExternalStaticFunction("MoveToWalkableArea", (void *)MoveToWalkableArea);
	ccAddExternalStaticFunction("NewRoom",(void *)NewRoom);
	ccAddExternalStaticFunction("NewRoomEx",(void *)NewRoomEx);
	ccAddExternalStaticFunction("NewRoomNPC",(void *)NewRoomNPC);
	ccAddExternalStaticFunction("ObjectOff",(void *)ObjectOff);
	ccAddExternalStaticFunction("ObjectOn",(void *)ObjectOn);
	ccAddExternalStaticFunction("ParseText",(void *)ParseText);
	ccAddExternalStaticFunction("PauseGame",(void *)PauseGame);
	ccAddExternalStaticFunction("PlayAmbientSound",(void *)PlayAmbientSound);
	ccAddExternalStaticFunction("PlayFlic",(void *)play_flc_file);
	ccAddExternalStaticFunction("PlayMP3File",(void *)PlayMP3File);
	ccAddExternalStaticFunction("PlayMusic",(void *)PlayMusicResetQueue);
	ccAddExternalStaticFunction("PlayMusicQueued",(void *)PlayMusicQueued);
	ccAddExternalStaticFunction("PlaySilentMIDI",(void *)PlaySilentMIDI);
	ccAddExternalStaticFunction("PlaySound",(void *)play_sound);
	ccAddExternalStaticFunction("PlaySoundEx",(void *)PlaySoundEx);
	ccAddExternalStaticFunction("PlaySpeech",(void *)__scr_play_speech);
	ccAddExternalStaticFunction("PlayVideo",(void *)scrPlayVideo);
	ccAddExternalStaticFunction("ProcessClick",(void *)ProcessClick);
	ccAddExternalStaticFunction("QuitGame",(void *)QuitGame);
	ccAddExternalStaticFunction("Random",(void *)__Rand);
	ccAddExternalStaticFunction("RawClearScreen", (void *)RawClear);
	ccAddExternalStaticFunction("RawDrawCircle",(void *)RawDrawCircle);
	ccAddExternalStaticFunction("RawDrawFrameTransparent",(void *)RawDrawFrameTransparent);
	ccAddExternalStaticFunction("RawDrawImage", (void *)RawDrawImage);
	ccAddExternalStaticFunction("RawDrawImageOffset", (void *)RawDrawImageOffset);
	ccAddExternalStaticFunction("RawDrawImageResized", (void *)RawDrawImageResized);
	ccAddExternalStaticFunction("RawDrawImageTransparent", (void *)RawDrawImageTransparent);
	ccAddExternalStaticFunction("RawDrawLine", (void *)RawDrawLine);
	ccAddExternalStaticFunction("RawDrawRectangle", (void *)RawDrawRectangle);
	ccAddExternalStaticFunction("RawDrawTriangle", (void *)RawDrawTriangle);
	ccAddExternalStaticFunction("RawPrint", (void *)RawPrint);
	ccAddExternalStaticFunction("RawPrintMessageWrapped", (void *)RawPrintMessageWrapped);
	ccAddExternalStaticFunction("RawRestoreScreen", (void *)RawRestoreScreen);
	ccAddExternalStaticFunction("RawRestoreScreenTinted", (void *)RawRestoreScreenTinted);
	ccAddExternalStaticFunction("RawSaveScreen", (void *)RawSaveScreen);
	ccAddExternalStaticFunction("RawSetColor", (void *)RawSetColor);
	ccAddExternalStaticFunction("RawSetColorRGB", (void *)RawSetColorRGB);
	ccAddExternalStaticFunction("RefreshMouse",(void *)RefreshMouse);
	ccAddExternalStaticFunction("ReleaseCharacterView",(void *)ReleaseCharacterView);
	ccAddExternalStaticFunction("ReleaseViewport",(void *)ReleaseViewport);
	ccAddExternalStaticFunction("RemoveObjectTint",(void *)RemoveObjectTint);
	ccAddExternalStaticFunction("RemoveOverlay",(void *)RemoveOverlay);
	ccAddExternalStaticFunction("RemoveWalkableArea",(void *)RemoveWalkableArea);
	ccAddExternalStaticFunction("ResetRoom",(void *)ResetRoom);
	ccAddExternalStaticFunction("RestartGame",(void *)restart_game);
	ccAddExternalStaticFunction("RestoreGameDialog",(void *)restore_game_dialog);
	ccAddExternalStaticFunction("RestoreGameSlot",(void *)RestoreGameSlot);
	ccAddExternalStaticFunction("RestoreWalkableArea",(void *)RestoreWalkableArea);
	ccAddExternalStaticFunction("RunAGSGame", (void *)RunAGSGame);
	ccAddExternalStaticFunction("RunCharacterInteraction",(void *)RunCharacterInteraction);
	ccAddExternalStaticFunction("RunDialog",(void *)RunDialog);
	ccAddExternalStaticFunction("RunHotspotInteraction", (void *)RunHotspotInteraction);
	ccAddExternalStaticFunction("RunInventoryInteraction", (void *)RunInventoryInteraction);
	ccAddExternalStaticFunction("RunObjectInteraction", (void *)RunObjectInteraction);
	ccAddExternalStaticFunction("RunRegionInteraction", (void *)RunRegionInteraction);
	ccAddExternalStaticFunction("Said",(void *)Said);
	ccAddExternalStaticFunction("SaidUnknownWord",(void *)SaidUnknownWord);
	ccAddExternalStaticFunction("SaveCursorForLocationChange",(void *)SaveCursorForLocationChange);
	ccAddExternalStaticFunction("SaveGameDialog",(void *)save_game_dialog);
	ccAddExternalStaticFunction("SaveGameSlot",(void *)save_game);
	ccAddExternalStaticFunction("SaveScreenShot",(void *)SaveScreenShot);
	ccAddExternalStaticFunction("SeekMIDIPosition", (void *)SeekMIDIPosition);
	ccAddExternalStaticFunction("SeekMODPattern",(void *)SeekMODPattern);
	ccAddExternalStaticFunction("SeekMP3PosMillis", (void *)SeekMP3PosMillis);
	ccAddExternalStaticFunction("SetActiveInventory",(void *)SetActiveInventory);
	ccAddExternalStaticFunction("SetAmbientTint",(void *)SetAmbientTint);
	ccAddExternalStaticFunction("SetAreaLightLevel",(void *)SetAreaLightLevel);
	ccAddExternalStaticFunction("SetAreaScaling",(void *)SetAreaScaling);
	ccAddExternalStaticFunction("SetBackgroundFrame",(void *)SetBackgroundFrame);
	ccAddExternalStaticFunction("SetButtonPic",(void *)SetButtonPic);
	ccAddExternalStaticFunction("SetButtonText",(void *)SetButtonText);
	ccAddExternalStaticFunction("SetChannelVolume",(void *)SetChannelVolume);
	ccAddExternalStaticFunction("SetCharacterBaseline",(void *)SetCharacterBaseline);
	ccAddExternalStaticFunction("SetCharacterClickable",(void *)SetCharacterClickable);
	ccAddExternalStaticFunction("SetCharacterFrame",(void *)SetCharacterFrame);
	ccAddExternalStaticFunction("SetCharacterIdle",(void *)SetCharacterIdle);
	ccAddExternalStaticFunction("SetCharacterIgnoreLight",(void *)SetCharacterIgnoreLight);
	ccAddExternalStaticFunction("SetCharacterIgnoreWalkbehinds",(void *)SetCharacterIgnoreWalkbehinds);
	ccAddExternalStaticFunction("SetCharacterProperty",(void *)SetCharacterProperty);
	ccAddExternalStaticFunction("SetCharacterBlinkView",(void *)SetCharacterBlinkView);
	ccAddExternalStaticFunction("SetCharacterSpeechView",(void *)SetCharacterSpeechView);
	ccAddExternalStaticFunction("SetCharacterSpeed",(void *)SetCharacterSpeed);
	ccAddExternalStaticFunction("SetCharacterSpeedEx",(void *)SetCharacterSpeedEx);
	ccAddExternalStaticFunction("SetCharacterTransparency",(void *)SetCharacterTransparency);
	ccAddExternalStaticFunction("SetCharacterView",(void *)SetCharacterView);
	ccAddExternalStaticFunction("SetCharacterViewEx",(void *)SetCharacterViewEx);
	ccAddExternalStaticFunction("SetCharacterViewOffset",(void *)SetCharacterViewOffset);
	ccAddExternalStaticFunction("SetCursorMode",(void *)set_cursor_mode);
	ccAddExternalStaticFunction("SetDefaultCursor",(void *)set_default_cursor);
	ccAddExternalStaticFunction("SetDialogOption",(void *)SetDialogOption);
	ccAddExternalStaticFunction("SetDigitalMasterVolume",(void *)SetDigitalMasterVolume);
	ccAddExternalStaticFunction("SetFadeColor",(void *)SetFadeColor);
	ccAddExternalStaticFunction("SetFrameSound",(void *)SetFrameSound);
	ccAddExternalStaticFunction("SetGameOption",(void *)SetGameOption);
	ccAddExternalStaticFunction("SetGameSpeed",(void *)SetGameSpeed);
	ccAddExternalStaticFunction("SetGlobalInt",(void *)SetGlobalInt);
	ccAddExternalStaticFunction("SetGlobalString",(void *)SetGlobalString);
	ccAddExternalStaticFunction("SetGraphicalVariable",(void *)SetGraphicalVariable);
	ccAddExternalStaticFunction("SetGUIBackgroundPic", (void *)SetGUIBackgroundPic);
	ccAddExternalStaticFunction("SetGUIClickable", (void *)SetGUIClickable);
	ccAddExternalStaticFunction("SetGUIObjectEnabled",(void *)SetGUIObjectEnabled);
	ccAddExternalStaticFunction("SetGUIObjectPosition",(void *)SetGUIObjectPosition);
	ccAddExternalStaticFunction("SetGUIObjectSize",(void *)SetGUIObjectSize);
	ccAddExternalStaticFunction("SetGUIPosition",(void *)SetGUIPosition);
	ccAddExternalStaticFunction("SetGUISize",(void *)SetGUISize);
	ccAddExternalStaticFunction("SetGUITransparency", (void *)SetGUITransparency);
	ccAddExternalStaticFunction("SetGUIZOrder", (void *)SetGUIZOrder);
	ccAddExternalStaticFunction("SetInvItemName",(void *)SetInvItemName);
	ccAddExternalStaticFunction("SetInvItemPic",(void *)set_inv_item_pic);
	ccAddExternalStaticFunction("SetInvDimensions",(void *)SetInvDimensions);
	ccAddExternalStaticFunction("SetLabelColor",(void *)SetLabelColor);
	ccAddExternalStaticFunction("SetLabelFont",(void *)SetLabelFont);
	ccAddExternalStaticFunction("SetLabelText",(void *)SetLabelText);
	ccAddExternalStaticFunction("SetMouseBounds",(void *)SetMouseBounds);
	ccAddExternalStaticFunction("SetMouseCursor",(void *)set_mouse_cursor);
	ccAddExternalStaticFunction("SetMousePosition",(void *)SetMousePosition);
	ccAddExternalStaticFunction("SetMultitaskingMode",(void *)SetMultitasking);
	ccAddExternalStaticFunction("SetMusicMasterVolume",(void *)SetMusicMasterVolume);
	ccAddExternalStaticFunction("SetMusicRepeat",(void *)SetMusicRepeat);
	ccAddExternalStaticFunction("SetMusicVolume",(void *)SetMusicVolume);
	ccAddExternalStaticFunction("SetNextCursorMode", (void *)SetNextCursor);
	ccAddExternalStaticFunction("SetNextScreenTransition",(void *)SetNextScreenTransition);
	ccAddExternalStaticFunction("SetNormalFont", (void *)SetNormalFont);
	ccAddExternalStaticFunction("SetObjectBaseline",(void *)SetObjectBaseline);
	ccAddExternalStaticFunction("SetObjectClickable",(void *)SetObjectClickable);
	ccAddExternalStaticFunction("SetObjectFrame",(void *)SetObjectFrame);
	ccAddExternalStaticFunction("SetObjectGraphic",(void *)SetObjectGraphic);
	ccAddExternalStaticFunction("SetObjectIgnoreWalkbehinds",(void *)SetObjectIgnoreWalkbehinds);
	ccAddExternalStaticFunction("SetObjectPosition",(void *)SetObjectPosition);
	ccAddExternalStaticFunction("SetObjectTint",(void *)SetObjectTint);
	ccAddExternalStaticFunction("SetObjectTransparency",(void *)SetObjectTransparency);
	ccAddExternalStaticFunction("SetObjectView",(void *)SetObjectView);
	//  ccAddExternalStaticFunction("SetPalette",scSetPal);
	ccAddExternalStaticFunction("SetPalRGB",(void *)SetPalRGB);
	ccAddExternalStaticFunction("SetPlayerCharacter",(void *)SetPlayerCharacter);
	ccAddExternalStaticFunction("SetRegionTint",(void *)SetRegionTint);
	ccAddExternalStaticFunction("SetRestartPoint",(void *)SetRestartPoint);
	ccAddExternalStaticFunction("SetScreenTransition",(void *)SetScreenTransition);
	ccAddExternalStaticFunction("SetSkipSpeech",(void *)SetSkipSpeech);
	ccAddExternalStaticFunction("SetSliderValue",(void *)SetSliderValue);
	ccAddExternalStaticFunction("SetSoundVolume",(void *)SetSoundVolume);
	ccAddExternalStaticFunction("SetSpeechFont", (void *)SetSpeechFont);
	ccAddExternalStaticFunction("SetSpeechStyle", (void *)SetSpeechStyle);
	ccAddExternalStaticFunction("SetSpeechVolume",(void *)SetSpeechVolume);
	ccAddExternalStaticFunction("SetTalkingColor",(void *)SetTalkingColor);
	ccAddExternalStaticFunction("SetTextBoxFont",(void *)SetTextBoxFont);
	ccAddExternalStaticFunction("SetTextBoxText",(void *)SetTextBoxText);
	ccAddExternalStaticFunction("SetTextOverlay",(void *)SetTextOverlay);
	ccAddExternalStaticFunction("SetTextWindowGUI",(void *)SetTextWindowGUI);
	ccAddExternalStaticFunction("SetTimer",(void *)script_SetTimer);
	ccAddExternalStaticFunction("SetViewport",(void *)SetViewport);
	ccAddExternalStaticFunction("SetVoiceMode",(void *)SetVoiceMode);
	ccAddExternalStaticFunction("SetWalkBehindBase",(void *)SetWalkBehindBase);
	ccAddExternalStaticFunction("ShakeScreen",(void *)ShakeScreen);
	ccAddExternalStaticFunction("ShakeScreenBackground",(void *)ShakeScreenBackground);
	ccAddExternalStaticFunction("ShowMouseCursor",(void *)ShowMouseCursor);
	ccAddExternalStaticFunction("SkipUntilCharacterStops",(void *)SkipUntilCharacterStops);
	ccAddExternalStaticFunction("StartCutscene", (void *)StartCutscene);
	ccAddExternalStaticFunction("StartRecording", (void *)scStartRecording);
	ccAddExternalStaticFunction("StopAmbientSound",(void *)StopAmbientSound);
	ccAddExternalStaticFunction("StopChannel",(void *)stop_and_destroy_channel);
	ccAddExternalStaticFunction("StopDialog",(void *)StopDialog);
	ccAddExternalStaticFunction("StopMoving",(void *)StopMoving);
	ccAddExternalStaticFunction("StopMusic", (void *)scr_StopMusic);
	ccAddExternalStaticFunction("StopObjectMoving",(void *)StopObjectMoving);
	ccAddExternalStaticFunction("StrCat",(void *)_sc_strcat);
	ccAddExternalStaticFunction("StrCaseComp",(void *)stricmp);
	ccAddExternalStaticFunction("StrComp",(void *)strcmp);
	ccAddExternalStaticFunction("StrContains",(void *)StrContains);
	ccAddExternalStaticFunction("StrCopy",(void *)_sc_strcpy);
	ccAddExternalStaticFunction("StrFormat",(void *)_sc_sprintf);
	ccAddExternalStaticFunction("StrGetCharAt", (void *)StrGetCharAt);
	ccAddExternalStaticFunction("StringToInt",(void *)StringToInt);
	ccAddExternalStaticFunction("StrLen",(void *)strlen);
	ccAddExternalStaticFunction("StrSetCharAt", (void *)StrSetCharAt);
	ccAddExternalStaticFunction("StrToLowerCase", (void *)_sc_strlower);
	ccAddExternalStaticFunction("StrToUpperCase", (void *)_sc_strupper);
	ccAddExternalStaticFunction("TintScreen",(void *)TintScreen);
	ccAddExternalStaticFunction("UnPauseGame",(void *)UnPauseGame);
	ccAddExternalStaticFunction("UpdateInventory", (void *)update_invorder);
	ccAddExternalStaticFunction("UpdatePalette",(void *)UpdatePalette);
	ccAddExternalStaticFunction("Wait",(void *)scrWait);
	ccAddExternalStaticFunction("WaitKey",(void *)WaitKey);
	ccAddExternalStaticFunction("WaitMouseKey",(void *)WaitMouseKey);

	ccAddExternalData("game",&play);
	ccAddExternalData("gs_globals",&play.globalvars[0]);
	ccAddExternalData("mouse",&scmouse);
	ccAddExternalData("palette",&palette[0]);
	ccAddExternalData("system",&scsystem);
	ccAddExternalData("savegameindex",&play.filenumbers[0]);
}
