
//=============================================================================
//
// Exporting global script functions
//
//=============================================================================

// the ^n after the function name is the number of params
// this is to allow an extra parameter to be added in a later
// version without screwing up the stack in previous versions
// (just export both the ^n and the ^m as seperate funcs)

#include "script/symbol_registry.h"
#include <string.h>
#include "wgt2allg.h"
#include "acrun/ac_gamestate.h"

void register_global_script_functions()
{
	scAdd_External_Symbol("AbortGame",(void *)_sc_AbortGame);
	scAdd_External_Symbol("AddInventory",(void *)add_inventory);
	scAdd_External_Symbol("AddInventoryToCharacter",(void *)AddInventoryToCharacter);
	scAdd_External_Symbol("AnimateButton",(void *)AnimateButton);
	scAdd_External_Symbol("AnimateCharacter",(void *)scAnimateCharacter);
	scAdd_External_Symbol("AnimateCharacterEx",(void *)AnimateCharacterEx);
	scAdd_External_Symbol("AnimateObject",(void *)AnimateObject);
	scAdd_External_Symbol("AnimateObjectEx",(void *)AnimateObjectEx);
	scAdd_External_Symbol("AreCharactersColliding",(void *)AreCharactersColliding);
	scAdd_External_Symbol("AreCharObjColliding",(void *)AreCharObjColliding);
	scAdd_External_Symbol("AreObjectsColliding",(void *)AreObjectsColliding);
	scAdd_External_Symbol("AreThingsOverlapping",(void *)AreThingsOverlapping);
	scAdd_External_Symbol("CallRoomScript",(void *)CallRoomScript);
	scAdd_External_Symbol("CDAudio",(void *)cd_manager);
	scAdd_External_Symbol("CentreGUI",(void *)CentreGUI);
	scAdd_External_Symbol("ChangeCharacterView",(void *)ChangeCharacterView);
	scAdd_External_Symbol("ChangeCursorGraphic",(void *)ChangeCursorGraphic);
	scAdd_External_Symbol("ChangeCursorHotspot",(void *)ChangeCursorHotspot);
	scAdd_External_Symbol("ClaimEvent",(void *)ClaimEvent);
	scAdd_External_Symbol("CreateGraphicOverlay",(void *)CreateGraphicOverlay);
	scAdd_External_Symbol("CreateTextOverlay",(void *)CreateTextOverlay);
	scAdd_External_Symbol("CyclePalette",(void *)CyclePalette);
	scAdd_External_Symbol("Debug",(void *)script_debug);
	scAdd_External_Symbol("DeleteSaveSlot",(void *)DeleteSaveSlot);
	scAdd_External_Symbol("DeleteSprite",(void *)free_dynamic_sprite);
	scAdd_External_Symbol("DisableCursorMode",(void *)disable_cursor_mode);
	scAdd_External_Symbol("DisableGroundLevelAreas",(void *)DisableGroundLevelAreas);
	scAdd_External_Symbol("DisableHotspot",(void *)DisableHotspot);
	scAdd_External_Symbol("DisableInterface",(void *)DisableInterface);
	scAdd_External_Symbol("DisableRegion",(void *)DisableRegion);
	scAdd_External_Symbol("Display",(void *)Display);
	scAdd_External_Symbol("DisplayAt",(void *)DisplayAt);
	scAdd_External_Symbol("DisplayAtY",(void *)DisplayAtY);
	scAdd_External_Symbol("DisplayMessage",(void *)DisplayMessage);
	scAdd_External_Symbol("DisplayMessageAtY",(void *)DisplayMessageAtY);
	scAdd_External_Symbol("DisplayMessageBar",(void *)DisplayMessageBar);
	scAdd_External_Symbol("DisplaySpeech",(void *)__sc_displayspeech);
	scAdd_External_Symbol("DisplaySpeechAt", (void *)DisplaySpeechAt);
	scAdd_External_Symbol("DisplaySpeechBackground",(void *)DisplaySpeechBackground);
	scAdd_External_Symbol("DisplayThought",(void *)DisplayThought);
	scAdd_External_Symbol("DisplayTopBar",(void *)DisplayTopBar);
	scAdd_External_Symbol("EnableCursorMode",(void *)enable_cursor_mode);
	scAdd_External_Symbol("EnableGroundLevelAreas",(void *)EnableGroundLevelAreas);
	scAdd_External_Symbol("EnableHotspot",(void *)EnableHotspot);
	scAdd_External_Symbol("EnableInterface",(void *)EnableInterface);
	scAdd_External_Symbol("EnableRegion",(void *)EnableRegion);
	scAdd_External_Symbol("EndCutscene", (void *)EndCutscene);
	scAdd_External_Symbol("FaceCharacter",(void *)FaceCharacter);
	scAdd_External_Symbol("FaceLocation",(void *)FaceLocation);
	scAdd_External_Symbol("FadeIn",(void *)FadeIn);
	scAdd_External_Symbol("FadeOut",(void *)my_fade_out);
	scAdd_External_Symbol("FileClose",(void *)FileClose);
	scAdd_External_Symbol("FileIsEOF",(void *)FileIsEOF);
	scAdd_External_Symbol("FileIsError",(void *)FileIsError);
	scAdd_External_Symbol("FileOpen",(void *)FileOpen);
	scAdd_External_Symbol("FileRead",(void *)FileRead);
	scAdd_External_Symbol("FileReadInt",(void *)FileReadInt);
	scAdd_External_Symbol("FileReadRawChar",(void *)FileReadRawChar);
	scAdd_External_Symbol("FileReadRawInt",(void *)FileReadRawInt);
	scAdd_External_Symbol("FileWrite",(void *)FileWrite);
	scAdd_External_Symbol("FileWriteInt",(void *)FileWriteInt);
	scAdd_External_Symbol("FileWriteRawChar",(void *)FileWriteRawChar);
	scAdd_External_Symbol("FileWriteRawLine", (void *)FileWriteRawLine);
	scAdd_External_Symbol("FindGUIID",(void *)FindGUIID);
	scAdd_External_Symbol("FlipScreen",(void *)FlipScreen);
	scAdd_External_Symbol("FloatToInt",(void *)FloatToInt);
	scAdd_External_Symbol("FollowCharacter",(void *)FollowCharacter);
	scAdd_External_Symbol("FollowCharacterEx",(void *)FollowCharacterEx);
	scAdd_External_Symbol("GetBackgroundFrame",(void *)GetBackgroundFrame);
	scAdd_External_Symbol("GetButtonPic",(void *)GetButtonPic);
	scAdd_External_Symbol("GetCharacterAt",(void *)GetCharacterAt);
	scAdd_External_Symbol("GetCharacterProperty",(void *)GetCharacterProperty);
	scAdd_External_Symbol("GetCharacterPropertyText",(void *)GetCharacterPropertyText);
	scAdd_External_Symbol("GetCurrentMusic",(void *)GetCurrentMusic);
	scAdd_External_Symbol("GetCursorMode",(void *)GetCursorMode);
	scAdd_External_Symbol("GetDialogOption",(void *)GetDialogOption);
	scAdd_External_Symbol("GetGameOption",(void *)GetGameOption);
	scAdd_External_Symbol("GetGameParameter",(void *)GetGameParameter);
	scAdd_External_Symbol("GetGameSpeed",(void *)GetGameSpeed);
	scAdd_External_Symbol("GetGlobalInt",(void *)GetGlobalInt);
	scAdd_External_Symbol("GetGlobalString",(void *)GetGlobalString);
	scAdd_External_Symbol("GetGraphicalVariable",(void *)GetGraphicalVariable);
	scAdd_External_Symbol("GetGUIAt", (void *)GetGUIAt);
	scAdd_External_Symbol("GetGUIObjectAt", (void *)GetGUIObjectAt);
	scAdd_External_Symbol("GetHotspotAt",(void *)GetHotspotAt);
	scAdd_External_Symbol("GetHotspotName",(void *)GetHotspotName);
	scAdd_External_Symbol("GetHotspotPointX",(void *)GetHotspotPointX);
	scAdd_External_Symbol("GetHotspotPointY",(void *)GetHotspotPointY);
	scAdd_External_Symbol("GetHotspotProperty",(void *)GetHotspotProperty);
	scAdd_External_Symbol("GetHotspotPropertyText",(void *)GetHotspotPropertyText);
	scAdd_External_Symbol("GetInvAt",(void *)GetInvAt);
	scAdd_External_Symbol("GetInvGraphic",(void *)GetInvGraphic);
	scAdd_External_Symbol("GetInvName",(void *)GetInvName);
	scAdd_External_Symbol("GetInvProperty",(void *)GetInvProperty);
	scAdd_External_Symbol("GetInvPropertyText",(void *)GetInvPropertyText);
	//scAdd_External_Symbol("GetLanguageString",(void *)GetLanguageString);
	scAdd_External_Symbol("GetLocationName",(void *)GetLocationName);
	scAdd_External_Symbol("GetLocationType",(void *)GetLocationType);
	scAdd_External_Symbol("GetMessageText", (void *)GetMessageText);
	scAdd_External_Symbol("GetMIDIPosition", (void *)GetMIDIPosition);
	scAdd_External_Symbol("GetMP3PosMillis", (void *)GetMP3PosMillis);
	scAdd_External_Symbol("GetObjectAt",(void *)GetObjectAt);
	scAdd_External_Symbol("GetObjectBaseline",(void *)GetObjectBaseline);
	scAdd_External_Symbol("GetObjectGraphic",(void *)GetObjectGraphic);
	scAdd_External_Symbol("GetObjectName",(void *)GetObjectName);
	scAdd_External_Symbol("GetObjectProperty",(void *)GetObjectProperty);
	scAdd_External_Symbol("GetObjectPropertyText",(void *)GetObjectPropertyText);
	scAdd_External_Symbol("GetObjectX",(void *)GetObjectX);
	scAdd_External_Symbol("GetObjectY",(void *)GetObjectY);
	//  scAdd_External_Symbol("GetPalette",(void *)scGetPal);
	scAdd_External_Symbol("GetPlayerCharacter",(void *)GetPlayerCharacter);
	scAdd_External_Symbol("GetRawTime",(void *)GetRawTime);
	scAdd_External_Symbol("GetRegionAt",(void *)GetRegionAt);
	scAdd_External_Symbol("GetRoomProperty",(void *)GetRoomProperty);
	scAdd_External_Symbol("GetRoomPropertyText",(void *)GetRoomPropertyText);
	scAdd_External_Symbol("GetSaveSlotDescription",(void *)GetSaveSlotDescription);
	scAdd_External_Symbol("GetScalingAt",(void *)GetScalingAt);
	scAdd_External_Symbol("GetSliderValue",(void *)GetSliderValue);
	scAdd_External_Symbol("GetTextBoxText",(void *)GetTextBoxText);
	scAdd_External_Symbol("GetTextHeight",(void *)GetTextHeight);
	scAdd_External_Symbol("GetTextWidth",(void *)GetTextWidth);
	scAdd_External_Symbol("GetTime",(void *)sc_GetTime);
	scAdd_External_Symbol("GetTranslation", (void *)get_translation);
	scAdd_External_Symbol("GetTranslationName", (void *)GetTranslationName);
	scAdd_External_Symbol("GetViewportX",(void *)GetViewportX);
	scAdd_External_Symbol("GetViewportY",(void *)GetViewportY);
	scAdd_External_Symbol("GetWalkableAreaAt",(void *)GetWalkableAreaAt);
	scAdd_External_Symbol("GiveScore",(void *)GiveScore);
	scAdd_External_Symbol("HasPlayerBeenInRoom",(void *)HasPlayerBeenInRoom);
	scAdd_External_Symbol("HideMouseCursor",(void *)HideMouseCursor);
	scAdd_External_Symbol("InputBox",(void *)sc_inputbox);
	scAdd_External_Symbol("InterfaceOff",(void *)InterfaceOff);
	scAdd_External_Symbol("InterfaceOn",(void *)InterfaceOn);
	scAdd_External_Symbol("IntToFloat",(void *)IntToFloat);
	scAdd_External_Symbol("InventoryScreen",(void *)sc_invscreen);
	scAdd_External_Symbol("IsButtonDown",(void *)IsButtonDown);
	scAdd_External_Symbol("IsChannelPlaying",(void *)IsChannelPlaying);
	scAdd_External_Symbol("IsGamePaused",(void *)IsGamePaused);
	scAdd_External_Symbol("IsGUIOn", (void *)IsGUIOn);
	scAdd_External_Symbol("IsInteractionAvailable", (void *)IsInteractionAvailable);
	scAdd_External_Symbol("IsInventoryInteractionAvailable", (void *)IsInventoryInteractionAvailable);
	scAdd_External_Symbol("IsInterfaceEnabled", (void *)IsInterfaceEnabled);
	scAdd_External_Symbol("IsKeyPressed",(void *)IsKeyPressed);
	scAdd_External_Symbol("IsMusicPlaying",(void *)IsMusicPlaying);
	scAdd_External_Symbol("IsMusicVoxAvailable",(void *)IsMusicVoxAvailable);
	scAdd_External_Symbol("IsObjectAnimating",(void *)IsObjectAnimating);
	scAdd_External_Symbol("IsObjectMoving",(void *)IsObjectMoving);
	scAdd_External_Symbol("IsObjectOn",(void *)IsObjectOn);
	scAdd_External_Symbol("IsOverlayValid",(void *)IsOverlayValid);
	scAdd_External_Symbol("IsSoundPlaying",(void *)IsSoundPlaying);
	scAdd_External_Symbol("IsTimerExpired",(void *)IsTimerExpired);
	scAdd_External_Symbol("IsTranslationAvailable", (void *)IsTranslationAvailable);
	scAdd_External_Symbol("IsVoxAvailable",(void *)IsVoxAvailable);
	scAdd_External_Symbol("ListBoxAdd", (void *)ListBoxAdd);
	scAdd_External_Symbol("ListBoxClear", (void *)ListBoxClear);
	scAdd_External_Symbol("ListBoxDirList", (void *)ListBoxDirList);
	scAdd_External_Symbol("ListBoxGetItemText", (void *)ListBoxGetItemText);
	scAdd_External_Symbol("ListBoxGetNumItems", (void *)ListBoxGetNumItems);
	scAdd_External_Symbol("ListBoxGetSelected", (void *)ListBoxGetSelected);
	scAdd_External_Symbol("ListBoxRemove", (void *)ListBoxRemove);
	scAdd_External_Symbol("ListBoxSaveGameList", (void *)ListBoxSaveGameList);
	scAdd_External_Symbol("ListBoxSetSelected", (void *)ListBoxSetSelected);
	scAdd_External_Symbol("ListBoxSetTopItem", (void *)ListBoxSetTopItem);
	scAdd_External_Symbol("LoadImageFile",(void *)LoadImageFile);
	scAdd_External_Symbol("LoadSaveSlotScreenshot",(void *)LoadSaveSlotScreenshot);
	scAdd_External_Symbol("LoseInventory",(void *)lose_inventory);
	scAdd_External_Symbol("LoseInventoryFromCharacter",(void *)LoseInventoryFromCharacter);
	scAdd_External_Symbol("MergeObject",(void *)MergeObject);
	scAdd_External_Symbol("MoveCharacter",(void *)MoveCharacter);
	scAdd_External_Symbol("MoveCharacterBlocking",(void *)MoveCharacterBlocking);
	scAdd_External_Symbol("MoveCharacterDirect",(void *)MoveCharacterDirect);
	scAdd_External_Symbol("MoveCharacterPath",(void *)MoveCharacterPath);
	scAdd_External_Symbol("MoveCharacterStraight",(void *)MoveCharacterStraight);
	scAdd_External_Symbol("MoveCharacterToHotspot",(void *)MoveCharacterToHotspot);
	scAdd_External_Symbol("MoveCharacterToObject",(void *)MoveCharacterToObject);
	scAdd_External_Symbol("MoveObject",(void *)MoveObject);
	scAdd_External_Symbol("MoveObjectDirect",(void *)MoveObjectDirect);
	scAdd_External_Symbol("MoveOverlay",(void *)MoveOverlay);
	scAdd_External_Symbol("MoveToWalkableArea", (void *)MoveToWalkableArea);
	scAdd_External_Symbol("NewRoom",(void *)NewRoom);
	scAdd_External_Symbol("NewRoomEx",(void *)NewRoomEx);
	scAdd_External_Symbol("NewRoomNPC",(void *)NewRoomNPC);
	scAdd_External_Symbol("ObjectOff",(void *)ObjectOff);
	scAdd_External_Symbol("ObjectOn",(void *)ObjectOn);
	scAdd_External_Symbol("ParseText",(void *)ParseText);
	scAdd_External_Symbol("PauseGame",(void *)PauseGame);
	scAdd_External_Symbol("PlayAmbientSound",(void *)PlayAmbientSound);
	scAdd_External_Symbol("PlayFlic",(void *)play_flc_file);
	scAdd_External_Symbol("PlayMP3File",(void *)PlayMP3File);
	scAdd_External_Symbol("PlayMusic",(void *)PlayMusicResetQueue);
	scAdd_External_Symbol("PlayMusicQueued",(void *)PlayMusicQueued);
	scAdd_External_Symbol("PlaySilentMIDI",(void *)PlaySilentMIDI);
	scAdd_External_Symbol("PlaySound",(void *)play_sound);
	scAdd_External_Symbol("PlaySoundEx",(void *)PlaySoundEx);
	scAdd_External_Symbol("PlaySpeech",(void *)__scr_play_speech);
	scAdd_External_Symbol("PlayVideo",(void *)scrPlayVideo);
	scAdd_External_Symbol("ProcessClick",(void *)ProcessClick);
	scAdd_External_Symbol("QuitGame",(void *)QuitGame);
	scAdd_External_Symbol("Random",(void *)__Rand);
	scAdd_External_Symbol("RawClearScreen", (void *)RawClear);
	scAdd_External_Symbol("RawDrawCircle",(void *)RawDrawCircle);
	scAdd_External_Symbol("RawDrawFrameTransparent",(void *)RawDrawFrameTransparent);
	scAdd_External_Symbol("RawDrawImage", (void *)RawDrawImage);
	scAdd_External_Symbol("RawDrawImageOffset", (void *)RawDrawImageOffset);
	scAdd_External_Symbol("RawDrawImageResized", (void *)RawDrawImageResized);
	scAdd_External_Symbol("RawDrawImageTransparent", (void *)RawDrawImageTransparent);
	scAdd_External_Symbol("RawDrawLine", (void *)RawDrawLine);
	scAdd_External_Symbol("RawDrawRectangle", (void *)RawDrawRectangle);
	scAdd_External_Symbol("RawDrawTriangle", (void *)RawDrawTriangle);
	scAdd_External_Symbol("RawPrint", (void *)RawPrint);
	scAdd_External_Symbol("RawPrintMessageWrapped", (void *)RawPrintMessageWrapped);
	scAdd_External_Symbol("RawRestoreScreen", (void *)RawRestoreScreen);
	scAdd_External_Symbol("RawRestoreScreenTinted", (void *)RawRestoreScreenTinted);
	scAdd_External_Symbol("RawSaveScreen", (void *)RawSaveScreen);
	scAdd_External_Symbol("RawSetColor", (void *)RawSetColor);
	scAdd_External_Symbol("RawSetColorRGB", (void *)RawSetColorRGB);
	scAdd_External_Symbol("RefreshMouse",(void *)RefreshMouse);
	scAdd_External_Symbol("ReleaseCharacterView",(void *)ReleaseCharacterView);
	scAdd_External_Symbol("ReleaseViewport",(void *)ReleaseViewport);
	scAdd_External_Symbol("RemoveObjectTint",(void *)RemoveObjectTint);
	scAdd_External_Symbol("RemoveOverlay",(void *)RemoveOverlay);
	scAdd_External_Symbol("RemoveWalkableArea",(void *)RemoveWalkableArea);
	scAdd_External_Symbol("ResetRoom",(void *)ResetRoom);
	scAdd_External_Symbol("RestartGame",(void *)restart_game);
	scAdd_External_Symbol("RestoreGameDialog",(void *)restore_game_dialog);
	scAdd_External_Symbol("RestoreGameSlot",(void *)RestoreGameSlot);
	scAdd_External_Symbol("RestoreWalkableArea",(void *)RestoreWalkableArea);
	scAdd_External_Symbol("RunAGSGame", (void *)RunAGSGame);
	scAdd_External_Symbol("RunCharacterInteraction",(void *)RunCharacterInteraction);
	scAdd_External_Symbol("RunDialog",(void *)RunDialog);
	scAdd_External_Symbol("RunHotspotInteraction", (void *)RunHotspotInteraction);
	scAdd_External_Symbol("RunInventoryInteraction", (void *)RunInventoryInteraction);
	scAdd_External_Symbol("RunObjectInteraction", (void *)RunObjectInteraction);
	scAdd_External_Symbol("RunRegionInteraction", (void *)RunRegionInteraction);
	scAdd_External_Symbol("Said",(void *)Said);
	scAdd_External_Symbol("SaidUnknownWord",(void *)SaidUnknownWord);
	scAdd_External_Symbol("SaveCursorForLocationChange",(void *)SaveCursorForLocationChange);
	scAdd_External_Symbol("SaveGameDialog",(void *)save_game_dialog);
	scAdd_External_Symbol("SaveGameSlot",(void *)save_game);
	scAdd_External_Symbol("SaveScreenShot",(void *)SaveScreenShot);
	scAdd_External_Symbol("SeekMIDIPosition", (void *)SeekMIDIPosition);
	scAdd_External_Symbol("SeekMODPattern",(void *)SeekMODPattern);
	scAdd_External_Symbol("SeekMP3PosMillis", (void *)SeekMP3PosMillis);
	scAdd_External_Symbol("SetActiveInventory",(void *)SetActiveInventory);
	scAdd_External_Symbol("SetAmbientTint",(void *)SetAmbientTint);
	scAdd_External_Symbol("SetAreaLightLevel",(void *)SetAreaLightLevel);
	scAdd_External_Symbol("SetAreaScaling",(void *)SetAreaScaling);
	scAdd_External_Symbol("SetBackgroundFrame",(void *)SetBackgroundFrame);
	scAdd_External_Symbol("SetButtonPic",(void *)SetButtonPic);
	scAdd_External_Symbol("SetButtonText",(void *)SetButtonText);
	scAdd_External_Symbol("SetChannelVolume",(void *)SetChannelVolume);
	scAdd_External_Symbol("SetCharacterBaseline",(void *)SetCharacterBaseline);
	scAdd_External_Symbol("SetCharacterClickable",(void *)SetCharacterClickable);
	scAdd_External_Symbol("SetCharacterFrame",(void *)SetCharacterFrame);
	scAdd_External_Symbol("SetCharacterIdle",(void *)SetCharacterIdle);
	scAdd_External_Symbol("SetCharacterIgnoreLight",(void *)SetCharacterIgnoreLight);
	scAdd_External_Symbol("SetCharacterIgnoreWalkbehinds",(void *)SetCharacterIgnoreWalkbehinds);
	scAdd_External_Symbol("SetCharacterProperty",(void *)SetCharacterProperty);
	scAdd_External_Symbol("SetCharacterBlinkView",(void *)SetCharacterBlinkView);
	scAdd_External_Symbol("SetCharacterSpeechView",(void *)SetCharacterSpeechView);
	scAdd_External_Symbol("SetCharacterSpeed",(void *)SetCharacterSpeed);
	scAdd_External_Symbol("SetCharacterSpeedEx",(void *)SetCharacterSpeedEx);
	scAdd_External_Symbol("SetCharacterTransparency",(void *)SetCharacterTransparency);
	scAdd_External_Symbol("SetCharacterView",(void *)SetCharacterView);
	scAdd_External_Symbol("SetCharacterViewEx",(void *)SetCharacterViewEx);
	scAdd_External_Symbol("SetCharacterViewOffset",(void *)SetCharacterViewOffset);
	scAdd_External_Symbol("SetCursorMode",(void *)set_cursor_mode);
	scAdd_External_Symbol("SetDefaultCursor",(void *)set_default_cursor);
	scAdd_External_Symbol("SetDialogOption",(void *)SetDialogOption);
	scAdd_External_Symbol("SetDigitalMasterVolume",(void *)SetDigitalMasterVolume);
	scAdd_External_Symbol("SetFadeColor",(void *)SetFadeColor);
	scAdd_External_Symbol("SetFrameSound",(void *)SetFrameSound);
	scAdd_External_Symbol("SetGameOption",(void *)SetGameOption);
	scAdd_External_Symbol("SetGameSpeed",(void *)SetGameSpeed);
	scAdd_External_Symbol("SetGlobalInt",(void *)SetGlobalInt);
	scAdd_External_Symbol("SetGlobalString",(void *)SetGlobalString);
	scAdd_External_Symbol("SetGraphicalVariable",(void *)SetGraphicalVariable);
	scAdd_External_Symbol("SetGUIBackgroundPic", (void *)SetGUIBackgroundPic);
	scAdd_External_Symbol("SetGUIClickable", (void *)SetGUIClickable);
	scAdd_External_Symbol("SetGUIObjectEnabled",(void *)SetGUIObjectEnabled);
	scAdd_External_Symbol("SetGUIObjectPosition",(void *)SetGUIObjectPosition);
	scAdd_External_Symbol("SetGUIObjectSize",(void *)SetGUIObjectSize);
	scAdd_External_Symbol("SetGUIPosition",(void *)SetGUIPosition);
	scAdd_External_Symbol("SetGUISize",(void *)SetGUISize);
	scAdd_External_Symbol("SetGUITransparency", (void *)SetGUITransparency);
	scAdd_External_Symbol("SetGUIZOrder", (void *)SetGUIZOrder);
	scAdd_External_Symbol("SetInvItemName",(void *)SetInvItemName);
	scAdd_External_Symbol("SetInvItemPic",(void *)set_inv_item_pic);
	scAdd_External_Symbol("SetInvDimensions",(void *)SetInvDimensions);
	scAdd_External_Symbol("SetLabelColor",(void *)SetLabelColor);
	scAdd_External_Symbol("SetLabelFont",(void *)SetLabelFont);
	scAdd_External_Symbol("SetLabelText",(void *)SetLabelText);
	scAdd_External_Symbol("SetMouseBounds",(void *)SetMouseBounds);
	scAdd_External_Symbol("SetMouseCursor",(void *)set_mouse_cursor);
	scAdd_External_Symbol("SetMousePosition",(void *)SetMousePosition);
	scAdd_External_Symbol("SetMultitaskingMode",(void *)SetMultitasking);
	scAdd_External_Symbol("SetMusicMasterVolume",(void *)SetMusicMasterVolume);
	scAdd_External_Symbol("SetMusicRepeat",(void *)SetMusicRepeat);
	scAdd_External_Symbol("SetMusicVolume",(void *)SetMusicVolume);
	scAdd_External_Symbol("SetNextCursorMode", (void *)SetNextCursor);
	scAdd_External_Symbol("SetNextScreenTransition",(void *)SetNextScreenTransition);
	scAdd_External_Symbol("SetNormalFont", (void *)SetNormalFont);
	scAdd_External_Symbol("SetObjectBaseline",(void *)SetObjectBaseline);
	scAdd_External_Symbol("SetObjectClickable",(void *)SetObjectClickable);
	scAdd_External_Symbol("SetObjectFrame",(void *)SetObjectFrame);
	scAdd_External_Symbol("SetObjectGraphic",(void *)SetObjectGraphic);
	scAdd_External_Symbol("SetObjectIgnoreWalkbehinds",(void *)SetObjectIgnoreWalkbehinds);
	scAdd_External_Symbol("SetObjectPosition",(void *)SetObjectPosition);
	scAdd_External_Symbol("SetObjectTint",(void *)SetObjectTint);
	scAdd_External_Symbol("SetObjectTransparency",(void *)SetObjectTransparency);
	scAdd_External_Symbol("SetObjectView",(void *)SetObjectView);
	//  scAdd_External_Symbol("SetPalette",scSetPal);
	scAdd_External_Symbol("SetPalRGB",(void *)SetPalRGB);
	scAdd_External_Symbol("SetPlayerCharacter",(void *)SetPlayerCharacter);
	scAdd_External_Symbol("SetRegionTint",(void *)SetRegionTint);
	scAdd_External_Symbol("SetRestartPoint",(void *)SetRestartPoint);
	scAdd_External_Symbol("SetScreenTransition",(void *)SetScreenTransition);
	scAdd_External_Symbol("SetSkipSpeech",(void *)SetSkipSpeech);
	scAdd_External_Symbol("SetSliderValue",(void *)SetSliderValue);
	scAdd_External_Symbol("SetSoundVolume",(void *)SetSoundVolume);
	scAdd_External_Symbol("SetSpeechFont", (void *)SetSpeechFont);
	scAdd_External_Symbol("SetSpeechStyle", (void *)SetSpeechStyle);
	scAdd_External_Symbol("SetSpeechVolume",(void *)SetSpeechVolume);
	scAdd_External_Symbol("SetTalkingColor",(void *)SetTalkingColor);
	scAdd_External_Symbol("SetTextBoxFont",(void *)SetTextBoxFont);
	scAdd_External_Symbol("SetTextBoxText",(void *)SetTextBoxText);
	scAdd_External_Symbol("SetTextOverlay",(void *)SetTextOverlay);
	scAdd_External_Symbol("SetTextWindowGUI",(void *)SetTextWindowGUI);
	scAdd_External_Symbol("SetTimer",(void *)script_SetTimer);
	scAdd_External_Symbol("SetViewport",(void *)SetViewport);
	scAdd_External_Symbol("SetVoiceMode",(void *)SetVoiceMode);
	scAdd_External_Symbol("SetWalkBehindBase",(void *)SetWalkBehindBase);
	scAdd_External_Symbol("ShakeScreen",(void *)ShakeScreen);
	scAdd_External_Symbol("ShakeScreenBackground",(void *)ShakeScreenBackground);
	scAdd_External_Symbol("ShowMouseCursor",(void *)ShowMouseCursor);
	scAdd_External_Symbol("SkipUntilCharacterStops",(void *)SkipUntilCharacterStops);
	scAdd_External_Symbol("StartCutscene", (void *)StartCutscene);
	scAdd_External_Symbol("StartRecording", (void *)scStartRecording);
	scAdd_External_Symbol("StopAmbientSound",(void *)StopAmbientSound);
	scAdd_External_Symbol("StopChannel",(void *)stop_and_destroy_channel);
	scAdd_External_Symbol("StopDialog",(void *)StopDialog);
	scAdd_External_Symbol("StopMoving",(void *)StopMoving);
	scAdd_External_Symbol("StopMusic", (void *)scr_StopMusic);
	scAdd_External_Symbol("StopObjectMoving",(void *)StopObjectMoving);
	scAdd_External_Symbol("StrCat",(void *)_sc_strcat);
	scAdd_External_Symbol("StrCaseComp",(void *)stricmp);
	scAdd_External_Symbol("StrComp",(void *)strcmp);
	scAdd_External_Symbol("StrContains",(void *)StrContains);
	scAdd_External_Symbol("StrCopy",(void *)_sc_strcpy);
	scAdd_External_Symbol("StrFormat",(void *)_sc_sprintf);
	scAdd_External_Symbol("StrGetCharAt", (void *)StrGetCharAt);
	scAdd_External_Symbol("StringToInt",(void *)StringToInt);
	scAdd_External_Symbol("StrLen",(void *)strlen);
	scAdd_External_Symbol("StrSetCharAt", (void *)StrSetCharAt);
	scAdd_External_Symbol("StrToLowerCase", (void *)_sc_strlower);
	scAdd_External_Symbol("StrToUpperCase", (void *)_sc_strupper);
	scAdd_External_Symbol("TintScreen",(void *)TintScreen);
	scAdd_External_Symbol("UnPauseGame",(void *)UnPauseGame);
	scAdd_External_Symbol("UpdateInventory", (void *)update_invorder);
	scAdd_External_Symbol("UpdatePalette",(void *)UpdatePalette);
	scAdd_External_Symbol("Wait",(void *)scrWait);
	scAdd_External_Symbol("WaitKey",(void *)WaitKey);
	scAdd_External_Symbol("WaitMouseKey",(void *)WaitMouseKey);
	scAdd_External_Symbol("game",&play);
	scAdd_External_Symbol("gs_globals",&play.globalvars[0]);
	scAdd_External_Symbol("mouse",&scmouse);
	scAdd_External_Symbol("palette",&palette[0]);
	scAdd_External_Symbol("system",&scsystem);
	scAdd_External_Symbol("savegameindex",&play.filenumbers[0]);
}
