#!/bin/sh
scriptpath=$(readlink -f "$0")
scriptdir=$(dirname "$scriptpath")

for arg; do
    if [ "$arg" = "--help" ]; then
        echo "Usage: $(basename "$scriptpath") [<ags options>]\n"
        break
    fi
done

if [ "$(uname -m)" = "x86_64" ]; then
    ALLEGRO_MODULES="$scriptdir/data/lib64" "$scriptdir/data/ags64" "$@" "$scriptdir/data/"
else
    ALLEGRO_MODULES="$scriptdir/data/lib32" "$scriptdir/data/ags32" "$@" "$scriptdir/data/"
fi
